# Generated by Django 5.1.5 on 2025-09-28 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
        ("bodegas", "0001_initial"),
    ]

    operations = [
        # Agregar nuevos campos como nullable
        migrations.AddField(
            model_name='inventario',
            name='bodega_destino',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='inventarios_destino',
                to='bodegas.bodega'
            ),
        ),
        migrations.AddField(
            model_name='inventario',
            name='bodega_origen',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='inventarios_origen',
                to='bodegas.bodega'
            ),
        ),
        migrations.AddField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name="Descripción del Movimiento"),
        ),
        migrations.AddField(
            model_name='stock',
            name='bodega',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='stocks',
                to='bodegas.bodega'
            ),
        ),
        # Renombrar stock_actual a cantidad
        migrations.RenameField(
            model_name='stock',
            old_name='stock_actual',
            new_name='cantidad',
        ),
    ]
