# Generated by Django 5.1.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_recreate_stock_table'),
    ]

    operations = [
        migrations.RunSQL(
            # Primero eliminar el índice que hace referencia a sucursal_id
            "DROP INDEX IF EXISTS inventario_inventario_sucursal_id_ec75080a;",
            reverse_sql="CREATE INDEX inventario_inventario_sucursal_id_ec75080a ON inventario_inventario (sucursal_id);"
        ),
        migrations.RunSQL(
            # Luego eliminar la columna sucursal_id de inventario_inventario
            "ALTER TABLE inventario_inventario DROP COLUMN sucursal_id;",
            reverse_sql="ALTER TABLE inventario_inventario ADD COLUMN sucursal_id bigint;"
        ),
    ]
