# Generated by Django 4.2.7 on 2025-09-29 13:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0007_alter_articulo_impuesto_especifico"),
        ("bodegas", "0002_remove_bodega_capacidad_maxima_and_more"),
        ("empresas", "0003_remove_empresa_color_primario_and_more"),
        ("inventario", "0005_remove_sucursal_from_inventario"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("empresa", "bodega", "articulo")},
        ),
        migrations.RemoveField(
            model_name="inventario",
            name="sucursal",
        ),
        migrations.AlterField(
            model_name="inventario",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmado", "Confirmado"),
                    ("cancelado", "Cancelado"),
                    ("completado", "Completado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="fecha_movimiento",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha del Movimiento"
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Cantidad",
            ),
        ),
        migrations.RemoveField(
            model_name="stock",
            name="sucursal",
        ),
    ]
