# Generated by Django 4.2.7 on 2025-09-29 13:31

import django.core.validators
from django.db import migrations, models, connection
import django.utils.timezone


def alter_stock_unique_together_safe(apps, schema_editor):
    """Alter unique together de forma segura, ignorando si el índice anterior no existe"""
    # Como la tabla fue recreada en la migración anterior, el índice antiguo ya no existe
    # Solo necesitamos crear el nuevo índice único
    vendor = schema_editor.connection.vendor
    
    # Verificar si el índice único ya existe
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE tablename = 'inventario_stock' 
                    AND indexname = 'inventario_stock_empresa_id_bodega_id_articulo_id_uniq'
                )
            """)
            index_exists = cursor.fetchone()[0]
        else:
            # Para SQLite, simplemente intentar crear
            index_exists = False
    
    # Si el índice no existe, crearlo
    if not index_exists:
        if vendor == 'postgresql':
            schema_editor.execute("""
                CREATE UNIQUE INDEX inventario_stock_empresa_id_bodega_id_articulo_id_uniq 
                ON inventario_stock (empresa_id, bodega_id, articulo_id);
            """)
        else:
            # Para SQLite, Django lo manejará automáticamente
            pass


def reverse_alter_stock_unique_together(apps, schema_editor):
    """Reversar el cambio"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0007_alter_articulo_impuesto_especifico"),
        ("bodegas", "0002_remove_bodega_capacidad_maxima_and_more"),
        ("empresas", "0003_remove_empresa_color_primario_and_more"),
        ("inventario", "0005_remove_sucursal_from_inventario"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(alter_stock_unique_together_safe, reverse_alter_stock_unique_together),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="stock",
                    unique_together={("empresa", "bodega", "articulo")},
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    lambda apps, schema_editor: None,  # No hacer nada en BD si la columna no existe
                    lambda apps, schema_editor: None
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="inventario",
                    name="sucursal",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="inventario",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmado", "Confirmado"),
                    ("cancelado", "Cancelado"),
                    ("completado", "Completado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="fecha_movimiento",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha del Movimiento"
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Cantidad",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    lambda apps, schema_editor: None,  # No hacer nada en BD si la columna no existe
                    lambda apps, schema_editor: None
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="stock",
                    name="sucursal",
                ),
            ],
        ),
    ]
