# Generated by Django 5.1.5 on 2025-09-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0006_alter_stock_unique_together_and_more"),
    ]

    operations = [
        # Esta migración marca la anterior como aplicada sin hacer cambios
        # ya que la restricción unique_together ya existe
    ]
