# Generated by Django 5.1.5 on 2025-09-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0007_auto_20250929_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="numero_folio",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Número de Folio"
            ),
        ),
    ]
