# Generated by Django 5.1.5 on 2025-10-15 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodegas", "0003_bodega_sucursal"),
        ("empresas", "0011_empresa_oficina_sii"),
        (
            "facturacion_electronica",
            "0004_documentotributarioelectronico_tipo_traslado",
        ),
        ("inventario", "0008_inventario_numero_folio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferenciaInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_folio",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Folio"
                    ),
                ),
                (
                    "fecha_transferencia",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Transferencia"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmado", "Confirmado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="confirmado",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "bodega_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferencias_destino",
                        to="bodegas.bodega",
                    ),
                ),
                (
                    "bodega_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferencias_origen",
                        to="bodegas.bodega",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferencias",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "guia_despacho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="Guía de Despacho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferencia de Inventario",
                "verbose_name_plural": "Transferencias de Inventario",
                "ordering": ["-fecha_transferencia"],
            },
        ),
        migrations.AddField(
            model_name="inventario",
            name="transferencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="inventario.transferenciainventario",
                verbose_name="Transferencia",
            ),
        ),
    ]
