# Generated by Django 5.2.7 on 2025-10-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodegas", "0004_alter_bodega_sucursal"),
        ("inventario", "0009_transferenciainventario_inventario_transferencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferenciainventario",
            name="bodega_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferencias_destino",
                to="bodegas.bodega",
            ),
        ),
    ]
