# Generated by Django 4.2.13 on 2026-04-02 04:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0018_agregar_sistema_ofertas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bodegas", "0004_alter_bodega_sucursal"),
        ("empresas", "0028_plansaas_empresa_auto_suspender_and_more"),
        ("inventario", "0010_alter_transferenciainventario_bodega_destino"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjusteStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_folio",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Folio"
                    ),
                ),
                (
                    "tipo_ajuste",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada de Mercadería (Suma al Stock)"),
                            ("salida", "Salida de Mercadería (Resta al Stock)"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Ajuste",
                    ),
                ),
                (
                    "fecha_ajuste",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Ajuste",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones / Motivo"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "bodega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustes_stock",
                        to="bodegas.bodega",
                        verbose_name="Bodega",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustes_stock",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de Stock",
                "verbose_name_plural": "Ajustes de Stock",
                "ordering": ["-fecha_ajuste", "-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DetalleAjuste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "comentario",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Comentario"
                    ),
                ),
                (
                    "ajuste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventario.ajustestock",
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_ajuste",
                        to="articulos.articulo",
                    ),
                ),
                (
                    "movimiento",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_ajuste_master",
                        to="inventario.inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Ajuste",
                "verbose_name_plural": "Detalles de Ajuste",
            },
        ),
    ]
