# Generated by Django 5.2.7 on 2026-06-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0028_plansaas_empresa_auto_suspender_and_more'),
        ('inventario', '0011_ajustestock_detalleajuste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustestock',
            name='numero_folio',
            field=models.CharField(max_length=20, verbose_name='Número de Folio'),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='numero_folio',
            field=models.CharField(max_length=20, verbose_name='Número de Folio'),
        ),
        migrations.AlterUniqueTogether(
            name='ajustestock',
            unique_together={('empresa', 'numero_folio')},
        ),
        migrations.AlterUniqueTogether(
            name='transferenciainventario',
            unique_together={('empresa', 'numero_folio')},
        ),
    ]
