# Generated by Django 5.2.7 on 2026-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_ajustestock_numero_folio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ajustestock',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transferenciainventario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ajustestock',
            name='numero_folio',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Folio'),
        ),
        migrations.AlterField(
            model_name='transferenciainventario',
            name='numero_folio',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Folio'),
        ),
    ]
