# Generated by Django 5.1.5 on 2025-10-07 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0007_empresa_ambiente_sii_empresa_certificado_digital_and_more"),
        ("ventas", "0007_venta_estado_cotizacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoCAF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("33", "Factura Electrónica"),
                            ("34", "Factura Exenta Electrónica"),
                            ("39", "Boleta Electrónica"),
                            ("41", "Boleta Exenta Electrónica"),
                            ("52", "Guía de Despacho Electrónica"),
                            ("56", "Nota de Débito Electrónica"),
                            ("61", "Nota de Crédito Electrónica"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("folio_desde", models.IntegerField(verbose_name="Folio Desde")),
                ("folio_hasta", models.IntegerField(verbose_name="Folio Hasta")),
                (
                    "cantidad_folios",
                    models.IntegerField(verbose_name="Cantidad de Folios"),
                ),
                (
                    "archivo_xml",
                    models.FileField(
                        upload_to="caf/", verbose_name="Archivo XML del CAF"
                    ),
                ),
                (
                    "contenido_caf",
                    models.TextField(verbose_name="Contenido XML del CAF"),
                ),
                (
                    "fecha_autorizacion",
                    models.DateField(verbose_name="Fecha de Autorización"),
                ),
                (
                    "firma_electronica",
                    models.TextField(verbose_name="Firma Electrónica (FRMA)"),
                ),
                (
                    "folios_utilizados",
                    models.IntegerField(default=0, verbose_name="Folios Utilizados"),
                ),
                ("folio_actual", models.IntegerField(verbose_name="Folio Actual")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("agotado", "Agotado"),
                            ("vencido", "Vencido"),
                            ("anulado", "Anulado"),
                        ],
                        default="activo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_carga",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Carga"
                    ),
                ),
                (
                    "fecha_agotamiento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Agotamiento"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos_caf",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "usuario_carga",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que Cargó",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo CAF",
                "verbose_name_plural": "Archivos CAF",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoTributarioElectronico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_dte",
                    models.CharField(
                        choices=[
                            ("33", "Factura Electrónica"),
                            ("34", "Factura Exenta Electrónica"),
                            ("39", "Boleta Electrónica"),
                            ("41", "Boleta Exenta Electrónica"),
                            ("52", "Guía de Despacho Electrónica"),
                            ("56", "Nota de Débito Electrónica"),
                            ("61", "Nota de Crédito Electrónica"),
                        ],
                        max_length=10,
                        verbose_name="Tipo DTE",
                    ),
                ),
                ("folio", models.IntegerField(verbose_name="Folio")),
                ("fecha_emision", models.DateField(verbose_name="Fecha de Emisión")),
                (
                    "rut_receptor",
                    models.CharField(max_length=12, verbose_name="RUT Receptor"),
                ),
                (
                    "razon_social_receptor",
                    models.CharField(
                        max_length=200, verbose_name="Razón Social Receptor"
                    ),
                ),
                (
                    "giro_receptor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Giro Receptor"
                    ),
                ),
                (
                    "direccion_receptor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dirección Receptor"
                    ),
                ),
                (
                    "comuna_receptor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Comuna Receptor"
                    ),
                ),
                (
                    "ciudad_receptor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ciudad Receptor"
                    ),
                ),
                (
                    "monto_neto",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Monto Neto"
                    ),
                ),
                (
                    "monto_exento",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Exento",
                    ),
                ),
                (
                    "monto_iva",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Monto IVA"
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Monto Total"
                    ),
                ),
                ("xml_dte", models.TextField(blank=True, verbose_name="XML del DTE")),
                (
                    "xml_firmado",
                    models.TextField(blank=True, verbose_name="XML Firmado"),
                ),
                (
                    "timbre_electronico",
                    models.TextField(
                        blank=True, verbose_name="Timbre Electrónico (TED)"
                    ),
                ),
                (
                    "estado_sii",
                    models.CharField(
                        choices=[
                            ("generado", "Generado"),
                            ("firmado", "Firmado"),
                            ("enviado", "Enviado al SII"),
                            ("aceptado", "Aceptado por SII"),
                            ("rechazado", "Rechazado por SII"),
                            ("anulado", "Anulado"),
                        ],
                        default="generado",
                        max_length=20,
                        verbose_name="Estado SII",
                    ),
                ),
                (
                    "track_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Track ID SII"
                    ),
                ),
                (
                    "fecha_envio_sii",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Envío al SII"
                    ),
                ),
                (
                    "fecha_respuesta_sii",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Respuesta SII"
                    ),
                ),
                (
                    "glosa_sii",
                    models.TextField(blank=True, verbose_name="Respuesta del SII"),
                ),
                (
                    "pdf_documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="dte_pdf/",
                        verbose_name="PDF del Documento",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "caf_utilizado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes",
                        to="facturacion_electronica.archivocaf",
                        verbose_name="CAF Utilizado",
                    ),
                ),
                (
                    "documento_referencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_relacionados",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="Documento de Referencia",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dtes",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creación",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dte",
                        to="ventas.venta",
                        verbose_name="Venta Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Tributario Electrónico",
                "verbose_name_plural": "Documentos Tributarios Electrónicos",
                "ordering": ["-fecha_emision", "-folio"],
            },
        ),
        migrations.CreateModel(
            name="AcuseRecibo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_acuse",
                    models.CharField(
                        choices=[
                            ("comercial", "Acuse Comercial"),
                            ("recibo", "Acuse de Recibo"),
                            ("reclamo", "Reclamo"),
                            ("aceptacion", "Aceptación Contenido"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Acuse",
                    ),
                ),
                ("xml_acuse", models.TextField(verbose_name="XML del Acuse")),
                (
                    "fecha_recepcion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Recepción"
                    ),
                ),
                (
                    "procesado",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "dte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acuses",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="DTE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acuse de Recibo",
                "verbose_name_plural": "Acuses de Recibo",
                "ordering": ["-fecha_recepcion"],
            },
        ),
        migrations.CreateModel(
            name="EnvioDTE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_documentos",
                    models.IntegerField(verbose_name="Cantidad de Documentos"),
                ),
                ("xml_envio", models.TextField(verbose_name="XML del Envío (SetDTE)")),
                ("fecha_envio", models.DateTimeField(verbose_name="Fecha de Envío")),
                (
                    "track_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Track ID"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviando", "Enviando"),
                            ("enviado", "Enviado"),
                            ("aceptado", "Aceptado"),
                            ("rechazado", "Rechazado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "xml_respuesta",
                    models.TextField(blank=True, verbose_name="XML de Respuesta"),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Respuesta"
                    ),
                ),
                (
                    "glosa_respuesta",
                    models.TextField(blank=True, verbose_name="Glosa de Respuesta"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "documentos",
                    models.ManyToManyField(
                        related_name="envios",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="Documentos",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="envios_dte",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Envío de DTE",
                "verbose_name_plural": "Envíos de DTE",
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.AddIndex(
            model_name="archivocaf",
            index=models.Index(
                fields=["empresa", "tipo_documento", "estado"],
                name="facturacion_empresa_6696ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="archivocaf",
            index=models.Index(
                fields=["folio_desde", "folio_hasta"],
                name="facturacion_folio_d_70fb8d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="archivocaf",
            unique_together={
                ("empresa", "tipo_documento", "folio_desde", "folio_hasta")
            },
        ),
        migrations.AddIndex(
            model_name="documentotributarioelectronico",
            index=models.Index(
                fields=["empresa", "tipo_dte", "folio"],
                name="facturacion_empresa_3a7dc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentotributarioelectronico",
            index=models.Index(
                fields=["estado_sii"], name="facturacion_estado__1a2014_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentotributarioelectronico",
            index=models.Index(
                fields=["fecha_emision"], name="facturacion_fecha_e_154608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentotributarioelectronico",
            index=models.Index(
                fields=["rut_receptor"], name="facturacion_rut_rec_fa67cb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentotributarioelectronico",
            unique_together={("empresa", "tipo_dte", "folio")},
        ),
    ]
