# Generated by Django 5.1.5 on 2025-10-07 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0008_empresa_alerta_folios_minimos"),
        ("facturacion_electronica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionAlertaFolios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("33", "Factura Electrónica"),
                            ("34", "Factura Exenta Electrónica"),
                            ("39", "Boleta Electrónica"),
                            ("41", "Boleta Exenta Electrónica"),
                            ("52", "Guía de Despacho Electrónica"),
                            ("56", "Nota de Débito Electrónica"),
                            ("61", "Nota de Crédito Electrónica"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "folios_minimos",
                    models.IntegerField(
                        default=20,
                        help_text="Cantidad de folios restantes para activar alerta",
                        verbose_name="Folios Mínimos para Alerta",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Alerta Activa"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas_folios",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Alerta de Folios",
                "verbose_name_plural": "Configuraciones de Alertas de Folios",
                "ordering": ["tipo_documento"],
                "unique_together": {("empresa", "tipo_documento")},
            },
        ),
    ]
