# Generated by Django 5.1.5 on 2025-10-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion_electronica", "0002_configuracionalertafolios"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="timbre_pdf417",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="dte/timbres/",
                verbose_name="Timbre PDF417",
            ),
        ),
    ]
