# Generated by Django 5.1.5 on 2025-10-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion_electronica",
            "0003_documentotributarioelectronico_timbre_pdf417",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="tipo_traslado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Venta"),
                    ("2", "Venta por efectuar (anticipada)"),
                    ("3", "Consignación"),
                    ("4", "Devolución"),
                    ("5", "Traslado interno"),
                    ("6", "Transformación de productos"),
                    ("7", "Entrega gratuita"),
                    ("8", "Otros"),
                ],
                help_text="Motivo de emisión de la guía (solo para tipo 52)",
                max_length=2,
                null=True,
                verbose_name="Tipo de Traslado",
            ),
        ),
    ]
