# Generated by Django 5.1.5 on 2025-10-18 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion_electronica",
            "0004_documentotributarioelectronico_tipo_traslado",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="comuna_emisor",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Comuna Emisor"
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="datos_pdf417",
            field=models.TextField(blank=True, verbose_name="Datos para PDF417"),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="direccion_emisor",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Dirección Emisor"
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="error_envio",
            field=models.TextField(blank=True, verbose_name="Error en Envío"),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="fecha_consulta_estado",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha Última Consulta Estado"
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="giro_emisor",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Giro Emisor"
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="razon_social_emisor",
            field=models.CharField(
                default="", max_length=200, verbose_name="Razón Social Emisor"
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="respuesta_sii",
            field=models.TextField(
                blank=True, verbose_name="Respuesta Completa del SII"
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="rut_emisor",
            field=models.CharField(
                default="", max_length=12, verbose_name="RUT Emisor"
            ),
        ),
        migrations.AlterField(
            model_name="documentotributarioelectronico",
            name="usuario_creacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario Creación",
            ),
        ),
    ]
