# Generated by Django 4.2.13 on 2025-10-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0017_alter_categoriaarticulo_codigo"),
        (
            "facturacion_electronica",
            "0005_documentotributarioelectronico_comuna_emisor_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleDocumentoTributarioElectronico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "impuesto_especifico",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("unidad_medida", models.CharField(blank=True, max_length=20)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="articulos.articulo",
                    ),
                ),
                (
                    "dte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="facturacion_electronica.documentotributarioelectronico",
                    ),
                ),
            ],
        ),
    ]
