# Generated by Django 4.2.13 on 2025-10-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_ruta"),
        ("ventas", "0020_notadebito_notadebitodetalle"),
        ("facturacion_electronica", "0006_detalledocumentotributarioelectronico"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="chofer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dtes_chofer",
                to="pedidos.chofer",
                verbose_name="Chofer Asignado",
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dtes_vehiculo",
                to="pedidos.vehiculo",
                verbose_name="Vehículo Asignado",
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dtes_vendedor",
                to="ventas.vendedor",
                verbose_name="Vendedor Responsable",
            ),
        ),
    ]
