# Generated by Django 4.2.13 on 2025-10-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion_electronica",
            "0007_documentotributarioelectronico_chofer_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="DetalleDocumentoTributarioElectronico",
        ),
    ]
