# Generated by Django 4.2.13 on 2025-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0026_remove_notadebitodetalle_articulo_and_more"),
        (
            "facturacion_electronica",
            "0008_delete_detalledocumentotributarioelectronico",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="orden_despacho",
            field=models.ManyToManyField(
                blank=True,
                related_name="dtes_despacho",
                to="ventas.venta",
                verbose_name="Documentos de Despacho Asociados (Ventas/Guías)",
            ),
        ),
    ]
