# Generated by Django 4.2.13 on 2025-11-02 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion_electronica",
            "0009_documentotributarioelectronico_orden_despacho",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="fecha",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha"
            ),
        ),
    ]
