# Generated by Django 4.2.13 on 2026-02-20 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0027_remove_empresa_impresora_boleta_nombre_and_more"),
        ("facturacion_electronica", "0011_add_sucursal_oculto_to_caf"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="archivocaf",
            name="facturacion_empresa_6696ab_idx",
        ),
        migrations.AlterUniqueTogether(
            name="archivocaf",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="archivocaf",
            name="sucursal",
            field=models.ForeignKey(
                help_text="Sucursal a la que pertenece este CAF",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archivos_caf",
                to="empresas.sucursal",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="documentotributarioelectronico",
            name="estado_sii",
            field=models.CharField(
                choices=[
                    ("generado", "Generado"),
                    ("firmado", "Firmado"),
                    ("enviando", "Enviando al SII"),
                    ("enviado", "Enviado al SII"),
                    ("aceptado", "Aceptado por SII"),
                    ("rechazado", "Rechazado por SII"),
                    ("pendiente", "Pendiente de Envío"),
                    ("anulado", "Anulado"),
                ],
                default="generado",
                max_length=20,
                verbose_name="Estado SII",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="archivocaf",
            unique_together={
                ("empresa", "sucursal", "tipo_documento", "folio_desde", "folio_hasta")
            },
        ),
        migrations.AddIndex(
            model_name="archivocaf",
            index=models.Index(
                fields=["empresa", "sucursal", "tipo_documento", "estado"],
                name="facturacion_empresa_bf9045_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="archivocaf",
            index=models.Index(
                fields=["sucursal", "estado", "oculto"],
                name="facturacion_sucursa_4c4b5c_idx",
            ),
        ),
    ]
