# Generated by Django 4.2.13 on 2026-02-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion_electronica",
            "0012_remove_archivocaf_facturacion_empresa_6696ab_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="archivocaf",
            name="fecha_vencimiento",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que vence el CAF (por defecto 6 meses desde autorización)",
                null=True,
                verbose_name="Fecha de Vencimiento",
            ),
        ),
    ]
