# Generated by Django 4.2.13 on 2026-02-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion_electronica", "0013_archivocaf_fecha_vencimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="nombre_chofer",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nombre Chofer"
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="patente_transporte",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Patente Vehículo"
            ),
        ),
        migrations.AddField(
            model_name="documentotributarioelectronico",
            name="rut_transportista",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="RUT Transportista"
            ),
        ),
    ]
