# Generated by Django 5.1.5 on 2025-09-28 01:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0003_remove_empresa_color_primario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bodega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Bodega"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, verbose_name="Código de Bodega"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=255, verbose_name="Email"),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Responsable"
                    ),
                ),
                (
                    "capacidad_maxima",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Capacidad Máxima",
                    ),
                ),
                (
                    "tipo_capacidad",
                    models.CharField(
                        choices=[
                            ("unidades", "Unidades"),
                            ("m3", "Metros Cúbicos"),
                            ("kg", "Kilogramos"),
                            ("litros", "Litros"),
                        ],
                        default="unidades",
                        max_length=20,
                        verbose_name="Tipo de Capacidad",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bodegas",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bodega",
                "verbose_name_plural": "Bodegas",
                "ordering": ["nombre"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
    ]
