# Generated by Django 5.1.5 on 2025-09-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodegas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bodega",
            name="capacidad_maxima",
        ),
        migrations.RemoveField(
            model_name="bodega",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="bodega",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="bodega",
            name="email",
        ),
        migrations.RemoveField(
            model_name="bodega",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="bodega",
            name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="bodega",
            name="responsable",
        ),
        migrations.RemoveField(
            model_name="bodega",
            name="telefono",
        ),
        migrations.RemoveField(
            model_name="bodega",
            name="tipo_capacidad",
        ),
        migrations.AlterField(
            model_name="bodega",
            name="codigo",
            field=models.CharField(max_length=20, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="bodega",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
    ]
