# Generated by Django 5.1.5 on 2025-10-15 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodegas", "0002_remove_bodega_capacidad_maxima_and_more"),
        ("empresas", "0011_empresa_oficina_sii"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodega",
            name="sucursal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bodegas",
                to="empresas.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
