# Generated by Django 5.1.5 on 2025-10-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodegas", "0003_bodega_sucursal"),
        ("empresas", "0011_empresa_oficina_sii"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodega",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal a la que pertenece esta bodega",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bodegas",
                to="empresas.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
