# Generated by Django 5.1.5 on 2025-09-30 02:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articulos", "0007_alter_articulo_impuesto_especifico"),
        ("bodegas", "0002_remove_bodega_capacidad_maxima_and_more"),
        ("empresas", "0005_remove_configuracionempresa_formato_boletas_and_more"),
        ("proveedores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("factura", "Factura"),
                            ("guia_despacho", "Guía de Despacho"),
                            ("nota_credito", "Nota de Crédito"),
                            ("nota_debito", "Nota de Débito"),
                            ("boleta", "Boleta"),
                            ("factura_exenta", "Factura Exenta"),
                            ("recibo", "Recibo"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=50, verbose_name="Número de Documento"),
                ),
                (
                    "rut_proveedor",
                    models.CharField(max_length=12, verbose_name="RUT Proveedor"),
                ),
                ("fecha_emision", models.DateField(verbose_name="Fecha de Emisión")),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "estado_documento",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("anulado", "Anulado"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado del Documento",
                    ),
                ),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("pagada", "Pagada"),
                            ("credito", "Crédito"),
                            ("parcial", "Pago Parcial"),
                            ("vencida", "Vencida"),
                        ],
                        default="credito",
                        max_length=20,
                        verbose_name="Estado de Pago",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "descuentos_totales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Descuentos Totales",
                    ),
                ),
                (
                    "impuestos_totales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuestos Totales",
                    ),
                ),
                (
                    "total_documento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Documento",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "archivo_documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos_compra/",
                        verbose_name="Archivo del Documento",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "en_cuenta_corriente",
                    models.BooleanField(
                        default=False, verbose_name="En Cuenta Corriente"
                    ),
                ),
                (
                    "fecha_registro_cc",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Registro CC"
                    ),
                ),
                (
                    "monto_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Pagado",
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "bodega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bodegas.bodega",
                        verbose_name="Bodega",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_compra_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Compra",
                "verbose_name_plural": "Documentos de Compra",
                "ordering": ["-fecha_creacion"],
                "unique_together": {("empresa", "numero_documento", "tipo_documento")},
            },
        ),
        migrations.CreateModel(
            name="HistorialPagoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "monto_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Monto Pagado",
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(max_length=50, verbose_name="Método de Pago"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "documento_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_pagos",
                        to="documentos.documentocompra",
                        verbose_name="Documento de Compra",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Pago",
                "verbose_name_plural": "Historial de Pagos",
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="ItemDocumentoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_articulo",
                    models.CharField(max_length=50, verbose_name="Código del Artículo"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "descuento_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Descuento (%)",
                    ),
                ),
                (
                    "impuesto_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=19,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Impuesto (%)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "descuento_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Descuento Monto",
                    ),
                ),
                (
                    "impuesto_monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Impuesto Monto"
                    ),
                ),
                (
                    "total_item",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Item"
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "documento_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="documentos.documentocompra",
                        verbose_name="Documento de Compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Documento de Compra",
                "verbose_name_plural": "Items de Documentos de Compra",
                "ordering": ["id"],
            },
        ),
    ]
