# Generated by Django 5.1.5 on 2025-09-30 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentocompra",
            name="sucursal",
        ),
    ]
