# Generated by Django 5.1.5 on 2025-09-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0002_remove_documentocompra_sucursal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentocompra",
            name="rut_proveedor",
        ),
    ]
