# Generated by Django 5.1.5 on 2025-09-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_remove_documentocompra_rut_proveedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemdocumentocompra",
            name="codigo_articulo",
        ),
        migrations.RemoveField(
            model_name="itemdocumentocompra",
            name="descripcion",
        ),
    ]
