# Generated by Django 5.1.5 on 2025-09-30 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0004_auto_20250929_2359"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentocompra",
            name="descuentos_totales",
            field=models.IntegerField(default=0, verbose_name="Descuentos Totales"),
        ),
        migrations.AlterField(
            model_name="documentocompra",
            name="impuestos_totales",
            field=models.IntegerField(default=0, verbose_name="Impuestos Totales"),
        ),
        migrations.AlterField(
            model_name="documentocompra",
            name="subtotal",
            field=models.IntegerField(default=0, verbose_name="Subtotal"),
        ),
        migrations.AlterField(
            model_name="documentocompra",
            name="total_documento",
            field=models.IntegerField(default=0, verbose_name="Total Documento"),
        ),
        migrations.AlterField(
            model_name="itemdocumentocompra",
            name="cantidad",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="itemdocumentocompra",
            name="descuento_monto",
            field=models.IntegerField(default=0, verbose_name="Descuento Monto"),
        ),
        migrations.AlterField(
            model_name="itemdocumentocompra",
            name="descuento_porcentaje",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Descuento (%)",
            ),
        ),
        migrations.AlterField(
            model_name="itemdocumentocompra",
            name="impuesto_monto",
            field=models.IntegerField(default=0, verbose_name="Impuesto Monto"),
        ),
        migrations.AlterField(
            model_name="itemdocumentocompra",
            name="impuesto_porcentaje",
            field=models.IntegerField(
                default=19,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Impuesto (%)",
            ),
        ),
        migrations.AlterField(
            model_name="itemdocumentocompra",
            name="precio_unitario",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.AlterField(
            model_name="itemdocumentocompra",
            name="subtotal",
            field=models.IntegerField(default=0, verbose_name="Subtotal"),
        ),
        migrations.AlterField(
            model_name="itemdocumentocompra",
            name="total_item",
            field=models.IntegerField(default=0, verbose_name="Total Item"),
        ),
    ]
