# Generated by Django 4.2.7 on 2025-10-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0005_alter_documentocompra_descuentos_totales_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentocompra",
            name="estado_documento",
            field=models.CharField(
                choices=[("activo", "Activo"), ("anulado", "Anulado")],
                default="activo",
                max_length=20,
                verbose_name="Estado del Documento",
            ),
        ),
        migrations.AlterField(
            model_name="documentocompra",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("credito", "Crédito"),
                    ("pagada", "Pagada"),
                ],
                default="pendiente",
                max_length=20,
                verbose_name="Estado de Pago",
            ),
        ),
    ]
