# Generated by Django 5.1.5 on 2025-10-04 21:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0006_alter_documentocompra_estado_documento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historialpagodocumento",
            name="metodo_pago",
        ),
        migrations.RemoveField(
            model_name="historialpagodocumento",
            name="monto_pagado",
        ),
        migrations.AddField(
            model_name="historialpagodocumento",
            name="monto_total_pagado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Monto Total Pagado",
            ),
        ),
        migrations.CreateModel(
            name="FormaPagoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("cheque", "Cheque"),
                            ("tarjeta_credito", "Tarjeta de Crédito"),
                            ("tarjeta_debito", "Tarjeta de Débito"),
                            ("deposito", "Depósito"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "numero_cheque",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de Cheque"
                    ),
                ),
                (
                    "banco_cheque",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Banco del Cheque"
                    ),
                ),
                (
                    "fecha_vencimiento_cheque",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "numero_transferencia",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Número de Transferencia",
                    ),
                ),
                (
                    "banco_transferencia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Banco de Transferencia",
                    ),
                ),
                (
                    "numero_tarjeta",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Tarjeta"
                    ),
                ),
                (
                    "codigo_autorizacion",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código de Autorización"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formas_pago",
                        to="documentos.historialpagodocumento",
                        verbose_name="Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forma de Pago",
                "verbose_name_plural": "Formas de Pago",
                "ordering": ["id"],
            },
        ),
    ]
