# Generated by Django 5.1.5 on 2025-10-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0007_remove_historialpagodocumento_metodo_pago_and_more"),
        ("ventas", "0007_venta_estado_cotizacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formapagopago",
            name="metodo_pago",
        ),
        migrations.AddField(
            model_name="formapagopago",
            name="forma_pago",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ventas.formapago",
                verbose_name="Forma de Pago",
            ),
        ),
    ]
