# Generated by Django 5.1.5 on 2025-10-06 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0006_alter_ordencompra_estado_orden"),
        ("documentos", "0008_remove_formapagopago_metodo_pago_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentocompra",
            name="orden_compra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_asociados",
                to="compras.ordencompra",
                verbose_name="Orden de Compra Asociada",
            ),
        ),
    ]
