# Generated by Django 4.2.13 on 2026-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0009_documentocompra_orden_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentocompra",
            name="descuento_monto_directo",
            field=models.IntegerField(default=0, verbose_name="Descuento Directo ($)"),
        ),
        migrations.AddField(
            model_name="documentocompra",
            name="descuento_porcentaje_1",
            field=models.IntegerField(default=0, verbose_name="Descuento 1 (%)"),
        ),
        migrations.AddField(
            model_name="documentocompra",
            name="descuento_porcentaje_2",
            field=models.IntegerField(default=0, verbose_name="Descuento 2 (%)"),
        ),
        migrations.AddField(
            model_name="documentocompra",
            name="descuento_porcentaje_3",
            field=models.IntegerField(default=0, verbose_name="Descuento 3 (%)"),
        ),
        migrations.AddField(
            model_name="documentocompra",
            name="impuesto_especifico",
            field=models.IntegerField(default=0, verbose_name="Impuesto Específico"),
        ),
        migrations.AddField(
            model_name="documentocompra",
            name="iva_ajustado",
            field=models.IntegerField(default=0, verbose_name="IVA Final"),
        ),
        migrations.AddField(
            model_name="documentocompra",
            name="neto_ajustado",
            field=models.IntegerField(default=0, verbose_name="Neto Final"),
        ),
        migrations.AlterField(
            model_name="documentocompra",
            name="descuentos_totales",
            field=models.IntegerField(default=0, verbose_name="Suma Descuentos"),
        ),
        migrations.AlterField(
            model_name="documentocompra",
            name="subtotal",
            field=models.IntegerField(default=0, verbose_name="Subtotal (Items Bruto)"),
        ),
    ]
