# Generated by Django 5.2.7 on 2026-06-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_documentocompra_descuento_monto_directo_and_more'),
        ('empresas', '0028_plansaas_empresa_auto_suspender_and_more'),
        ('proveedores', '0003_alter_proveedor_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentocompra',
            unique_together={('empresa', 'proveedor', 'numero_documento', 'tipo_documento')},
        ),
    ]
