# Generated by Django 5.1.5 on 2025-10-01 04:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0007_alter_articulo_impuesto_especifico"),
        ("clientes", "0003_alter_cliente_sitio_web"),
        ("empresas", "0005_remove_configuracionempresa_formato_boletas_and_more"),
        ("ventas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_venta",
                    models.CharField(max_length=20, verbose_name="Número de Venta"),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "neto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Neto",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="IVA",
                    ),
                ),
                (
                    "impuesto_especifico",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Impuesto Específico",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("confirmada", "Confirmada"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "forma_pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.formapago",
                        verbose_name="Forma de Pago",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creación",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.vendedor",
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-fecha_creacion"],
                "unique_together": {("empresa", "numero_venta")},
            },
        ),
        migrations.CreateModel(
            name="VentaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Precio Total",
                    ),
                ),
                (
                    "impuesto_especifico",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Impuesto Específico",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalles de Venta",
                "ordering": ["fecha_creacion"],
            },
        ),
    ]
