# Generated by Django 5.1.5 on 2025-10-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_remove_configuracionempresa_formato_boletas_and_more"),
        ("ventas", "0002_venta_ventadetalle"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("factura", "Factura"),
                    ("boleta", "Boleta"),
                    ("guia", "Guía de Despacho"),
                    ("cotizacion", "Cotización"),
                    ("vale", "Vale Facturable"),
                ],
                default="boleta",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.CreateModel(
            name="EstacionTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=10, verbose_name="Número de Estación"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Estación"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "puede_facturar",
                    models.BooleanField(
                        default=False, verbose_name="Puede Emitir Facturas"
                    ),
                ),
                (
                    "puede_boletar",
                    models.BooleanField(
                        default=True, verbose_name="Puede Emitir Boletas"
                    ),
                ),
                (
                    "puede_guia",
                    models.BooleanField(
                        default=False, verbose_name="Puede Emitir Guías"
                    ),
                ),
                (
                    "puede_cotizar",
                    models.BooleanField(
                        default=True, verbose_name="Puede Emitir Cotizaciones"
                    ),
                ),
                (
                    "puede_vale",
                    models.BooleanField(
                        default=False, verbose_name="Puede Emitir Vales"
                    ),
                ),
                (
                    "max_items_factura",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Máx. Items Factura"
                    ),
                ),
                (
                    "max_items_boleta",
                    models.PositiveIntegerField(
                        default=35, verbose_name="Máx. Items Boleta"
                    ),
                ),
                (
                    "max_items_guia",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Máx. Items Guía"
                    ),
                ),
                (
                    "max_items_cotizacion",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Máx. Items Cotización"
                    ),
                ),
                (
                    "max_items_vale",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Máx. Items Vale"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estación de Trabajo",
                "verbose_name_plural": "Estaciones de Trabajo",
                "ordering": ["numero"],
                "unique_together": {("empresa", "numero")},
            },
        ),
        migrations.AddField(
            model_name="venta",
            name="estacion_trabajo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ventas.estaciontrabajo",
                verbose_name="Estación de Trabajo",
            ),
        ),
    ]
