# Generated by Django 5.1.5 on 2025-10-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0003_venta_tipo_documento_estaciontrabajo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estaciontrabajo",
            name="correlativo_boleta",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Boleta"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="correlativo_cotizacion",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Cotización"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="correlativo_factura",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Factura"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="correlativo_guia",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Guía"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="correlativo_vale",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Vale"
            ),
        ),
    ]
