# Generated by Django 5.1.5 on 2025-10-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0004_estaciontrabajo_correlativo_boleta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estaciontrabajo",
            name="correlativo_boleta",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Interno Boleta"
            ),
        ),
        migrations.AlterField(
            model_name="estaciontrabajo",
            name="correlativo_cotizacion",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Interno Cotización"
            ),
        ),
        migrations.AlterField(
            model_name="estaciontrabajo",
            name="correlativo_factura",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Interno Factura"
            ),
        ),
        migrations.AlterField(
            model_name="estaciontrabajo",
            name="correlativo_guia",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Interno Guía"
            ),
        ),
        migrations.AlterField(
            model_name="estaciontrabajo",
            name="correlativo_vale",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo Interno Vale"
            ),
        ),
    ]
