# Generated by Django 5.1.5 on 2025-10-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0005_alter_estaciontrabajo_correlativo_boleta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estaciontrabajo",
            name="correlativo_boleta",
        ),
        migrations.RemoveField(
            model_name="estaciontrabajo",
            name="correlativo_cotizacion",
        ),
        migrations.RemoveField(
            model_name="estaciontrabajo",
            name="correlativo_factura",
        ),
        migrations.RemoveField(
            model_name="estaciontrabajo",
            name="correlativo_guia",
        ),
        migrations.RemoveField(
            model_name="estaciontrabajo",
            name="correlativo_vale",
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="correlativo_ticket",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Correlativo de Ticket"
            ),
        ),
    ]
