# Generated by Django 5.1.5 on 2025-10-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0006_remove_estaciontrabajo_correlativo_boleta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="estado_cotizacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendiente", "Pendiente"),
                    ("enviada", "Enviada"),
                    ("aceptada", "Aceptada"),
                    ("rechazada", "Rechazada"),
                    ("vencida", "Vencida"),
                    ("convertida", "Convertida en Venta"),
                ],
                default="pendiente",
                max_length=20,
                null=True,
                verbose_name="Estado Cotización",
            ),
        ),
    ]
