# Generated by Django 5.1.5 on 2025-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0007_venta_estado_cotizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="tipo_documento_planeado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("factura", "Factura"),
                    ("boleta", "Boleta"),
                    ("guia", "Guía de Despacho"),
                    ("cotizacion", "Cotización"),
                    ("vale", "Vale Facturable"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Documento Planeado",
            ),
        ),
    ]
