# Generated by Django 5.1.5 on 2025-10-14 00:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articulos",
            "0010_alter_articulo_codigo_alter_articulo_codigo_barras_and_more",
        ),
        ("clientes", "0004_alter_cliente_region"),
        ("empresas", "0011_empresa_oficina_sii"),
        ("ventas", "0008_venta_tipo_documento_planeado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Devolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_devolucion",
                    models.CharField(
                        max_length=50, verbose_name="Número de Devolución"
                    ),
                ),
                (
                    "fecha_devolucion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Devolución",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("defectuoso", "Producto Defectuoso"),
                            ("equivocado", "Producto Equivocado"),
                            ("insatisfaccion", "Insatisfacción del Cliente"),
                            ("garantia", "Garantía"),
                            ("otro", "Otro Motivo"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "descripcion_motivo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción del Motivo"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("procesada", "Procesada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto Total",
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoluciones",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "usuario_aprobacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Aprobación",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creación",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoluciones",
                        to="ventas.venta",
                        verbose_name="Venta Original",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolución",
                "verbose_name_plural": "Devoluciones",
                "ordering": ["-fecha_devolucion"],
                "unique_together": {("empresa", "numero_devolucion")},
            },
        ),
        migrations.CreateModel(
            name="DevolucionDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_devuelta",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Cantidad Devuelta",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "motivo_especifico",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Motivo Específico del Artículo",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "devolucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="ventas.devolucion",
                        verbose_name="Devolución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Devolución",
                "verbose_name_plural": "Detalles de Devoluciones",
                "ordering": ["id"],
            },
        ),
    ]
