# Generated by Django 5.1.5 on 2025-10-15 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0011_empresa_oficina_sii"),
        ("ventas", "0009_devolucion_devoluciondetalle"),
    ]

    operations = [
        migrations.AddField(
            model_name="estaciontrabajo",
            name="sucursal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estaciones_trabajo",
                to="empresas.sucursal",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="sucursal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to="empresas.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
