# Generated by Django 5.1.5 on 2025-10-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0011_empresa_oficina_sii"),
        ("ventas", "0010_estaciontrabajo_sucursal_venta_sucursal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estaciontrabajo",
            name="sucursal",
        ),
        migrations.AlterField(
            model_name="venta",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal donde se realizó la venta",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="empresas.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
