# Generated by Django 5.1.5 on 2025-10-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0011_remove_estaciontrabajo_sucursal_alter_venta_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="estaciontrabajo",
            name="modo_pos",
            field=models.CharField(
                choices=[
                    ("normal", "Normal - Cliente al final"),
                    ("con_cliente", "Con Cliente - Cliente al inicio"),
                ],
                default="normal",
                help_text="Normal: Cliente opcional al final. Con Cliente: Selección obligatoria al inicio para aplicar precios especiales.",
                max_length=20,
                verbose_name="Modo de Operación POS",
            ),
        ),
    ]
