# Generated by Django 5.1.5 on 2025-10-16 01:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articulos",
            "0010_alter_articulo_codigo_alter_articulo_codigo_barras_and_more",
        ),
        ("clientes", "0004_alter_cliente_region"),
        ("empresas", "0011_empresa_oficina_sii"),
        ("ventas", "0012_estaciontrabajo_modo_pos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrecioClienteArticulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_especial",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio personalizado para este cliente. Si no existe, se usa el precio general del artículo.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio Especial",
                    ),
                ),
                (
                    "descuento_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Descuento adicional sobre el precio especial (opcional)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Descuento Adicional (%)",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio Vigencia"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Fin Vigencia"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios_clientes",
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios_especiales",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="precios_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio Especial Cliente",
                "verbose_name_plural": "Precios Especiales Clientes",
                "ordering": ["cliente__nombre", "articulo__nombre"],
                "indexes": [
                    models.Index(
                        fields=["cliente", "articulo", "activo"],
                        name="ventas_prec_cliente_f94b9d_idx",
                    ),
                    models.Index(
                        fields=["empresa", "activo"],
                        name="ventas_prec_empresa_63d92d_idx",
                    ),
                ],
                "unique_together": {("empresa", "cliente", "articulo")},
            },
        ),
    ]
