# Generated by Django 5.1.5 on 2025-10-16 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0013_precioclientearticulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="tipo_despacho",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Despacho por cuenta del vendedor"),
                    ("2", "Despacho por cuenta del comprador"),
                    ("3", "Despacho por cuenta de terceros"),
                ],
                max_length=2,
                null=True,
                verbose_name="Tipo de Despacho",
            ),
        ),
        migrations.CreateModel(
            name="VentaReferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_referencia",
                    models.CharField(
                        choices=[
                            ("801", "Orden de Compra"),
                            ("802", "Nota de Pedido"),
                            ("803", "Contrato"),
                            ("804", "Resolución"),
                            ("805", "Proceso ChileCompra"),
                            ("806", "Ficha ChileCompra"),
                            ("807", "DUS"),
                            ("808", "B/L (Conocimiento de embarque)"),
                            ("809", "AWB (Air Will Bill)"),
                            ("810", "MIC/DTA"),
                            ("811", "Carta de Porte"),
                            (
                                "812",
                                "Resolución del SNA donde califica Servicios de Exportación",
                            ),
                            ("813", "Pasaporte"),
                            ("814", "Certificado de Depósito Bolsa Prod. Chile"),
                            ("815", "Vale de Prenda Bolsa Prod. Chile"),
                            ("HES", "Hoja de Entrada de Servicios"),
                            ("HEM", "Hoja de Entrada de Materiales"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Referencia",
                    ),
                ),
                (
                    "folio_referencia",
                    models.CharField(
                        max_length=50, verbose_name="Folio/Número de Referencia"
                    ),
                ),
                (
                    "fecha_referencia",
                    models.DateField(verbose_name="Fecha de Referencia"),
                ),
                (
                    "razon_referencia",
                    models.TextField(blank=True, verbose_name="Razón de la Referencia"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencias",
                        to="ventas.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referencia de Venta",
                "verbose_name_plural": "Referencias de Ventas",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
