# Generated by Django 5.1.5 on 2025-10-20 03:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0014_venta_tipo_despacho_ventareferencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="monto_pagado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Monto Pagado",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="saldo_pendiente",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Saldo Pendiente",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="tipo_despacho",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Venta"),
                    ("2", "Venta por efectuar (anticipada)"),
                    ("3", "Consignación"),
                    ("4", "Devolución"),
                    ("5", "Traslado interno"),
                    ("6", "Transformación de productos"),
                    ("7", "Entrega gratuita"),
                    ("8", "Otros"),
                ],
                max_length=2,
                null=True,
                verbose_name="Tipo de Despacho",
            ),
        ),
        migrations.AlterField(
            model_name="ventareferencia",
            name="tipo_referencia",
            field=models.CharField(
                choices=[
                    ("52", "Guía de Despacho"),
                    ("801", "Orden de Compra"),
                    ("802", "Nota de Pedido"),
                    ("803", "Contrato"),
                    ("804", "Resolución"),
                    ("805", "Proceso ChileCompra"),
                    ("806", "Ficha ChileCompra"),
                    ("807", "DUS"),
                    ("808", "B/L (Conocimiento de embarque)"),
                    ("809", "AWB (Air Will Bill)"),
                    ("810", "MIC/DTA"),
                    ("811", "Carta de Porte"),
                    (
                        "812",
                        "Resolución del SNA donde califica Servicios de Exportación",
                    ),
                    ("813", "Pasaporte"),
                    ("814", "Certificado de Depósito Bolsa Prod. Chile"),
                    ("815", "Vale de Prenda Bolsa Prod. Chile"),
                    ("HES", "Hoja de Entrada de Servicios"),
                    ("HEM", "Hoja de Entrada de Materiales"),
                ],
                max_length=10,
                verbose_name="Tipo de Referencia",
            ),
        ),
    ]
