# Generated by Django 5.1.5 on 2025-10-20 15:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0016_ordenproduccion_meses_garantia_and_more"),
        ("bodegas", "0004_alter_bodega_sucursal"),
        ("clientes", "0004_alter_cliente_region"),
        ("empresas", "0014_agregar_config_impresoras"),
        (
            "facturacion_electronica",
            "0005_documentotributarioelectronico_comuna_emisor_and_more",
        ),
        ("ventas", "0015_venta_monto_pagado_venta_saldo_pendiente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=20, verbose_name="N° Nota de Crédito"),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha Emisión"
                    ),
                ),
                (
                    "tipo_nc",
                    models.CharField(
                        choices=[
                            ("ANULA", "Anula Documento Completo"),
                            ("CORRIGE_MONTO", "Corrige Monto"),
                            ("CORRIGE_TEXTO", "Corrige Texto"),
                        ],
                        default="ANULA",
                        max_length=20,
                        verbose_name="Tipo de Nota de Crédito",
                    ),
                ),
                (
                    "tipo_doc_afectado",
                    models.CharField(
                        choices=[
                            ("33", "Factura Electrónica"),
                            ("39", "Boleta Electrónica"),
                            ("52", "Guía de Despacho Electrónica"),
                            ("46", "Factura de Compra Electrónica"),
                        ],
                        max_length=2,
                        verbose_name="Tipo Documento Afectado",
                    ),
                ),
                (
                    "numero_doc_afectado",
                    models.CharField(
                        max_length=20, verbose_name="N° Documento Afectado"
                    ),
                ),
                (
                    "fecha_doc_afectado",
                    models.DateField(verbose_name="Fecha Doc. Afectado"),
                ),
                (
                    "motivo",
                    models.TextField(verbose_name="Motivo de la Nota de Crédito"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="IVA",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("emitida", "Emitida"),
                            ("enviada_sii", "Enviada al SII"),
                            ("aceptada_sii", "Aceptada por SII"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "bodega",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bodegas.bodega",
                        verbose_name="Bodega",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "dte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_credito",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="DTE Generado",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_credito_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creación",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.vendedor",
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Crédito",
                "verbose_name_plural": "Notas de Crédito",
                "ordering": ["-fecha", "-numero"],
                "unique_together": {("empresa", "numero")},
            },
        ),
        migrations.CreateModel(
            name="NotaCreditoDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, verbose_name="Código")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="% Descuento",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "nota_credito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.notacredito",
                        verbose_name="Nota de Crédito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Nota de Crédito",
                "verbose_name_plural": "Detalles Notas de Crédito",
                "ordering": ["id"],
            },
        ),
    ]
