# Generated by Django 4.2.7 on 2025-10-22 00:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0016_notacredito_notacreditodetalle"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notacredito",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="notacredito",
            name="numero",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="N° Nota de Crédito"
            ),
        ),
        migrations.AlterField(
            model_name="notacreditodetalle",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="notacreditodetalle",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Precio Unitario",
            ),
        ),
    ]
