# Generated by Django 5.2.7 on 2025-10-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0014_agregar_config_impresoras"),
        ("ventas", "0018_estacion_cierre_directo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="venta",
            unique_together={("empresa", "tipo_documento", "numero_venta")},
        ),
    ]
