# Generated by Django 4.2.13 on 2025-10-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_ruta"),
        ("ventas", "0020_notadebito_notadebitodetalle"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="chofer",
            field=models.ForeignKey(
                blank=True,
                help_text="Chofer asignado para el despacho (si aplica)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas_chofer",
                to="pedidos.chofer",
                verbose_name="Chofer Asignado",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                help_text="Vehículo asignado para el despacho (si aplica)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas_vehiculo",
                to="pedidos.vehiculo",
                verbose_name="Vehículo Asignado",
            ),
        ),
    ]
