# Generated by Django 4.2.13 on 2025-10-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0021_venta_chofer_venta_vehiculo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="chofer",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="vehiculo",
        ),
    ]
