# Generated by Django 4.2.13 on 2025-10-29 23:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0022_remove_venta_chofer_remove_venta_vehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="descuento_total_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Descuento Total (%)",
            ),
        ),
        migrations.AddField(
            model_name="ventadetalle",
            name="descuento_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Descuento (%)",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Descuento (Monto)",
            ),
        ),
    ]
