# Generated by Django 4.2.13 on 2025-10-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0007_delete_hojaruta"),
        (
            "ventas",
            "0023_venta_descuento_total_pct_ventadetalle_descuento_pct_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="chofer",
            field=models.ForeignKey(
                blank=True,
                help_text="Chofer asignado para el despacho (si aplica)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas_chofer",
                to="pedidos.chofer",
                verbose_name="Chofer Asignado",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                help_text="Vehículo asignado para el despacho (si aplica)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas_vehiculo",
                to="pedidos.vehiculo",
                verbose_name="Vehículo Asignado",
            ),
        ),
    ]
