# Generated by Django 4.2.13 on 2025-10-31 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0024_venta_chofer_venta_vehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="factura_referenciada",
            field=models.ForeignKey(
                blank=True,
                help_text="Factura que incluyó esta guía",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guias_facturadas",
                to="ventas.venta",
                verbose_name="Factura Asociada",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="facturada",
            field=models.BooleanField(
                default=False,
                help_text="Indica si esta guía ya fue facturada",
                verbose_name="Facturada",
            ),
        ),
    ]
