# Generated by Django 4.2.13 on 2025-10-31 23:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0007_delete_hojaruta"),
        ("ventas", "0025_venta_factura_referenciada_venta_facturada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notadebitodetalle",
            name="articulo",
        ),
        migrations.RemoveField(
            model_name="notadebitodetalle",
            name="nota_debito",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="descuento_total_pct",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="factura_referenciada",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="facturada",
        ),
        migrations.RemoveField(
            model_name="ventadetalle",
            name="descuento_pct",
        ),
        migrations.AlterField(
            model_name="venta",
            name="chofer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pedidos.chofer",
                verbose_name="Chofer",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Descuento",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pedidos.vehiculo",
                verbose_name="Vehículo",
            ),
        ),
        migrations.DeleteModel(
            name="NotaDebito",
        ),
        migrations.DeleteModel(
            name="NotaDebitoDetalle",
        ),
    ]
