# Generated by Django 4.2.13 on 2025-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0026_remove_notadebitodetalle_articulo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="facturado",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el vale facturable ya fue procesado en caja",
                verbose_name="Facturado",
            ),
        ),
    ]
