# Generated by Django 4.2.13 on 2025-11-26 18:05

from django.db import migrations, models


def actualizar_tipo_documento_planeado(apps, schema_editor):
    """Actualizar vales existentes sin tipo_documento_planeado"""
    Venta = apps.get_model('ventas', 'Venta')
    # Actualizar vales sin tipo_documento_planeado
    Venta.objects.filter(
        tipo_documento='vale',
        tipo_documento_planeado__isnull=True
    ).update(tipo_documento_planeado='vale')
    
    # Actualizar otros documentos sin tipo_documento_planeado
    Venta.objects.filter(
        tipo_documento_planeado__isnull=True
    ).exclude(tipo_documento='vale').update(tipo_documento_planeado=models.F('tipo_documento'))


def reverse_actualizar_tipo_documento_planeado(apps, schema_editor):
    """Reversar la actualización (no necesario, pero incluido para completitud)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0027_agregar_campo_facturado"),
    ]

    operations = [
        # Primero actualizar datos existentes
        migrations.RunPython(actualizar_tipo_documento_planeado, reverse_actualizar_tipo_documento_planeado),
        # Luego cambiar el campo
        migrations.AlterField(
            model_name="venta",
            name="tipo_documento_planeado",
            field=models.CharField(
                choices=[
                    ("factura", "Factura"),
                    ("boleta", "Boleta"),
                    ("guia", "Guía de Despacho"),
                    ("cotizacion", "Cotización"),
                    ("vale", "Vale Facturable"),
                ],
                default="vale",
                help_text="Tipo de documento que se generará al procesar este vale",
                max_length=20,
                verbose_name="Tipo de Documento Planeado",
            ),
        ),
    ]
