# Generated by Django 4.2.13 on 2025-11-26 18:09

from django.db import migrations, models


def corregir_vales_con_tipo_vale(apps, schema_editor):
    """Corregir vales que tienen tipo_documento_planeado='vale' (no válido)"""
    Venta = apps.get_model('ventas', 'Venta')
    # Corregir vales que tienen tipo_documento_planeado='vale' (no tiene sentido)
    # Cambiarlos a 'boleta' por defecto
    vales_corregidos = Venta.objects.filter(
        tipo_documento='vale',
        tipo_documento_planeado='vale'
    ).update(tipo_documento_planeado='boleta')
    
    print(f"[MIGRACIÓN] Corregidos {vales_corregidos} vales con tipo_documento_planeado='vale'")


def reverse_corregir_vales_con_tipo_vale(apps, schema_editor):
    """Reversar la corrección (no necesario, pero incluido para completitud)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0028_tipo_documento_planeado_required"),
    ]

    operations = [
        # Primero corregir datos existentes
        migrations.RunPython(corregir_vales_con_tipo_vale, reverse_corregir_vales_con_tipo_vale),
        # Luego cambiar el default
        migrations.AlterField(
            model_name="venta",
            name="tipo_documento_planeado",
            field=models.CharField(
                choices=[
                    ("factura", "Factura"),
                    ("boleta", "Boleta"),
                    ("guia", "Guía de Despacho"),
                    ("cotizacion", "Cotización"),
                    ("vale", "Vale Facturable"),
                ],
                default="boleta",
                help_text="Tipo de documento que se generará al procesar este vale (factura, boleta, guía o cotización)",
                max_length=20,
                verbose_name="Tipo de Documento Planeado",
            ),
        ),
    ]
