# Generated by Django 4.2.13 on 2025-12-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0029_corregir_tipo_documento_planeado_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="estaciontrabajo",
            name="codigo_comodin",
            field=models.CharField(
                default="999999",
                help_text="Código especial que permite crear productos con nombre y precio personalizado en el POS",
                max_length=50,
                verbose_name="Código Comodín",
            ),
        ),
    ]
