# Generated by Django 4.2.13 on 2026-02-13 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0027_remove_empresa_impresora_boleta_nombre_and_more"),
        ("ventas", "0030_add_codigo_comodin_estacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendedorUbicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        decimal_places=9, max_digits=12, verbose_name="Latitud"
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        decimal_places=9, max_digits=12, verbose_name="Longitud"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha Registro"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicaciones",
                        to="ventas.vendedor",
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación de Vendedor",
                "verbose_name_plural": "Ubicaciones de Vendedores",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
