# Generated by Django 4.2.13 on 2026-02-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0027_remove_empresa_impresora_boleta_nombre_and_more"),
        ("ventas", "0031_vendedorubicacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispositivoMovil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        max_length=100,
                        verbose_name="Identificador Único (UUID/Fingerprint)",
                    ),
                ),
                (
                    "nombre_dispositivo",
                    models.CharField(
                        help_text="Ej: Samsung S23 de Pedro",
                        max_length=100,
                        verbose_name="Nombre del Dispositivo",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Modelo/SO"
                    ),
                ),
                (
                    "autorizado",
                    models.BooleanField(
                        default=False, verbose_name="Autorizado para Vender"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("ultima_sincronizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.vendedor",
                        verbose_name="Vendedor Asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo Móvil",
                "verbose_name_plural": "Dispositivos Móviles",
                "unique_together": {("empresa", "unique_id")},
            },
        ),
    ]
