# Generated by Django 4.2.13 on 2026-02-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0032_dispositivomovil"),
    ]

    operations = [
        migrations.AddField(
            model_name="estaciontrabajo",
            name="max_items_ticket",
            field=models.PositiveIntegerField(
                default=50, verbose_name="Máx. Items Ticket"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="puede_ticket",
            field=models.BooleanField(
                default=True, verbose_name="Puede Emitir Tickets Facturables"
            ),
        ),
        migrations.AlterField(
            model_name="estaciontrabajo",
            name="puede_vale",
            field=models.BooleanField(
                default=False, verbose_name="Puede Emitir Vales Internos"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("factura", "Factura"),
                    ("boleta", "Boleta"),
                    ("guia", "Guía de Despacho"),
                    ("cotizacion", "Cotización"),
                    ("ticket", "Ticket Facturable"),
                    ("vale", "Vale Interno"),
                ],
                default="boleta",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="tipo_documento_planeado",
            field=models.CharField(
                choices=[
                    ("factura", "Factura"),
                    ("boleta", "Boleta"),
                    ("guia", "Guía de Despacho"),
                    ("cotizacion", "Cotización"),
                    ("ticket", "Ticket Facturable"),
                    ("vale", "Vale Interno"),
                ],
                default="boleta",
                help_text="Tipo de documento que se generará al procesar este vale (factura, boleta, guía o cotización)",
                max_length=20,
                verbose_name="Tipo de Documento Planeado",
            ),
        ),
    ]
