# Generated by Django 4.2.13 on 2026-02-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0033_estaciontrabajo_max_items_ticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notacredito",
            name="tipo_doc_afectado",
            field=models.CharField(
                choices=[
                    ("33", "Factura Electrónica"),
                    ("39", "Boleta Electrónica"),
                    ("52", "Guía de Despacho Electrónica"),
                    ("46", "Factura de Compra Electrónica"),
                    ("56", "Nota de Débito Electrónica"),
                    ("61", "Nota de Crédito Electrónica"),
                ],
                max_length=2,
                verbose_name="Tipo Documento Afectado",
            ),
        ),
    ]
