# Generated by Django 4.2.13 on 2026-02-20 01:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion_electronica",
            "0012_remove_archivocaf_facturacion_empresa_6696ab_idx_and_more",
        ),
        ("articulos", "0018_agregar_sistema_ofertas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0027_remove_empresa_impresora_boleta_nombre_and_more"),
        ("clientes", "0008_cliente_vendedor"),
        ("bodegas", "0004_alter_bodega_sucursal"),
        ("ventas", "0034_alter_notacredito_tipo_doc_afectado"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaDebito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="N° Nota de Débito",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha Emisión"
                    ),
                ),
                (
                    "tipo_nd",
                    models.CharField(
                        choices=[
                            ("AUMENTA_MONTO", "Aumenta Monto del Documento"),
                            ("CORRIGE_TEXTO", "Corrige Texto del Documento"),
                            ("INTERESES", "Intereses por Mora"),
                            ("OTROS", "Otros Motivos"),
                        ],
                        default="AUMENTA_MONTO",
                        max_length=20,
                        verbose_name="Tipo de Nota de Débito",
                    ),
                ),
                (
                    "tipo_doc_afectado",
                    models.CharField(
                        choices=[
                            ("33", "Factura Electrónica"),
                            ("39", "Boleta Electrónica"),
                            ("52", "Guía de Despacho Electrónica"),
                            ("46", "Factura de Compra Electrónica"),
                            ("56", "Nota de Débito Electrónica"),
                            ("61", "Nota de Crédito Electrónica"),
                        ],
                        max_length=2,
                        verbose_name="Tipo Documento Afectado",
                    ),
                ),
                (
                    "numero_doc_afectado",
                    models.CharField(
                        max_length=20, verbose_name="N° Documento Afectado"
                    ),
                ),
                (
                    "fecha_doc_afectado",
                    models.DateField(verbose_name="Fecha Doc. Afectado"),
                ),
                (
                    "motivo",
                    models.TextField(verbose_name="Motivo de la Nota de Débito"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="IVA",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("emitida", "Emitida"),
                            ("enviada_sii", "Enviada al SII"),
                            ("aceptada_sii", "Aceptada por SII"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "bodega",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bodegas.bodega",
                        verbose_name="Bodega",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "dte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_debito",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="DTE Generado",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_debito_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creación",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.vendedor",
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Débito",
                "verbose_name_plural": "Notas de Débito",
                "ordering": ["-fecha", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="NotaDebitoDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, verbose_name="Código")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="% Descuento",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Total"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "nota_debito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.notadebito",
                        verbose_name="Nota de Débito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Nota de Débito",
                "verbose_name_plural": "Detalles Notas de Débito",
                "ordering": ["id"],
            },
        ),
    ]
