# Generated by Django 4.2.13 on 2026-04-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0035_notadebito_notadebitodetalle"),
    ]

    operations = [
        migrations.AddField(
            model_name="estaciontrabajo",
            name="copias_boleta",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Copias Boleta"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="copias_cotizacion",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Copias Cotización"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="copias_factura",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Copias Factura"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="copias_guia",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Copias Guía"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="copias_ticket",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Copias Ticket"
            ),
        ),
        migrations.AddField(
            model_name="estaciontrabajo",
            name="copias_vale",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Copias Vale"
            ),
        ),
    ]
