# Generated by Django 4.2.13 on 2026-04-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0036_estaciontrabajo_copias_boleta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estaciontrabajo",
            name="copias_notacredito",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Copias Nota Crédito"
            ),
        ),
    ]
