# Generated by Django 5.2.7 on 2026-06-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0038_ventadetalle_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventadetalle',
            name='descripcion',
        ),
    ]
