# Generated by Django 5.1.5 on 2025-10-16 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "articulos",
            "0010_alter_articulo_codigo_alter_articulo_codigo_barras_and_more",
        ),
        ("bodegas", "0004_alter_bodega_sucursal"),
        ("clientes", "0004_alter_cliente_region"),
        ("empresas", "0011_empresa_oficina_sii"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pedido",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Pedido"
                    ),
                ),
                (
                    "fecha_pedido",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Pedido",
                    ),
                ),
                (
                    "fecha_entrega_estimada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Estimada"
                    ),
                ),
                (
                    "numero_oc_cliente",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="N° OC Cliente"
                    ),
                ),
                (
                    "fecha_oc_cliente",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha OC Cliente"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("confirmada", "Confirmada"),
                            ("en_proceso", "En Proceso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("subtotal", models.IntegerField(default=0, verbose_name="Subtotal")),
                (
                    "descuentos_totales",
                    models.IntegerField(default=0, verbose_name="Descuentos Totales"),
                ),
                (
                    "impuestos_totales",
                    models.IntegerField(default=0, verbose_name="Impuestos Totales"),
                ),
                (
                    "total_pedido",
                    models.IntegerField(default=0, verbose_name="Total Pedido"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "condiciones_pago",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Condiciones de Pago"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "bodega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bodegas.bodega",
                        verbose_name="Bodega",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes_pedido",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Pedido",
                "verbose_name_plural": "Órdenes de Pedido",
                "ordering": ["-fecha_pedido", "-numero_pedido"],
            },
        ),
        migrations.CreateModel(
            name="ItemOrdenPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cantidad"
                    ),
                ),
                (
                    "precio_unitario",
                    models.IntegerField(verbose_name="Precio Unitario"),
                ),
                (
                    "descuento_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Descuento %",
                    ),
                ),
                (
                    "impuesto_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=19,
                        max_digits=5,
                        verbose_name="Impuesto %",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Observaciones"
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "orden_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.ordenpedido",
                        verbose_name="Orden de Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Orden de Pedido",
                "verbose_name_plural": "Items de Orden de Pedido",
            },
        ),
    ]
