# Generated by Django 4.2.13 on 2025-10-25 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturacion_electronica",
            "0005_documentotributarioelectronico_comuna_emisor_and_more",
        ),
        ("empresas", "0014_agregar_config_impresoras"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenDespacho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_despacho",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Despacho"
                    ),
                ),
                (
                    "fecha_despacho",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Despacho",
                    ),
                ),
                (
                    "fecha_entrega_estimada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Estimada"
                    ),
                ),
                (
                    "fecha_entrega_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Real"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_preparacion", "En Preparación"),
                            ("despachado", "Despachado"),
                            ("en_transito", "En Tránsito"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "transportista",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Transportista"
                    ),
                ),
                (
                    "numero_guia_transporte",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Número de Guía de Transporte",
                    ),
                ),
                (
                    "patente_vehiculo",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Patente del Vehículo"
                    ),
                ),
                (
                    "conductor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Conductor"
                    ),
                ),
                (
                    "direccion_entrega",
                    models.TextField(blank=True, verbose_name="Dirección de Entrega"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despachos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes_despacho",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "orden_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despachos",
                        to="pedidos.ordenpedido",
                        verbose_name="Orden de Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Despacho",
                "verbose_name_plural": "Órdenes de Despacho",
                "ordering": ["-fecha_despacho", "-numero_despacho"],
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenDespacho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cantidad a Despachar",
                    ),
                ),
                (
                    "lote",
                    models.CharField(blank=True, max_length=100, verbose_name="Lote"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"tipo_dte__in": ["33", "34"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_despacho_factura",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="Factura",
                    ),
                ),
                (
                    "guia_despacho",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"tipo_dte": "52"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_despacho_guia",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="Guía de Despacho",
                    ),
                ),
                (
                    "item_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despachos",
                        to="pedidos.itemordenpedido",
                        verbose_name="Item del Pedido",
                    ),
                ),
                (
                    "orden_despacho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pedidos.ordendespacho",
                        verbose_name="Orden de Despacho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Orden de Despacho",
                "verbose_name_plural": "Detalles de Órdenes de Despacho",
                "ordering": ["id"],
            },
        ),
    ]
