# Generated by Django 4.2.13 on 2025-10-26 01:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0014_agregar_config_impresoras"),
        ("pedidos", "0002_ordendespacho_detalleordendespacho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordendespacho",
            name="conductor",
        ),
        migrations.RemoveField(
            model_name="ordendespacho",
            name="numero_guia_transporte",
        ),
        migrations.RemoveField(
            model_name="ordendespacho",
            name="patente_vehiculo",
        ),
        migrations.RemoveField(
            model_name="ordendespacho",
            name="transportista",
        ),
        migrations.AddField(
            model_name="ordendespacho",
            name="transportista_externo",
            field=models.CharField(
                blank=True,
                help_text="Solo si el transporte es externo",
                max_length=200,
                verbose_name="Transportista Externo",
            ),
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patente",
                    models.CharField(
                        help_text="Ejemplo: ABCD12",
                        max_length=10,
                        verbose_name="Patente",
                    ),
                ),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        choices=[
                            ("camion", "Camión"),
                            ("camioneta", "Camioneta"),
                            ("furgon", "Furgón"),
                            ("auto", "Automóvil"),
                            ("moto", "Motocicleta"),
                            ("otro", "Otro"),
                        ],
                        default="camioneta",
                        max_length=20,
                        verbose_name="Tipo de Vehículo",
                    ),
                ),
                (
                    "marca",
                    models.CharField(blank=True, max_length=100, verbose_name="Marca"),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=100, verbose_name="Modelo"),
                ),
                ("año", models.IntegerField(blank=True, null=True, verbose_name="Año")),
                (
                    "capacidad_carga",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Capacidad de Carga (kg)",
                    ),
                ),
                (
                    "capacidad_volumen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Capacidad de Volumen (m³)",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, verbose_name="Color"),
                ),
                (
                    "numero_motor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de Motor"
                    ),
                ),
                (
                    "numero_chasis",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de Chasis"
                    ),
                ),
                (
                    "revision_tecnica_vencimiento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Vencimiento Revisión Técnica",
                    ),
                ),
                (
                    "permiso_circulacion_vencimiento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Vencimiento Permiso de Circulación",
                    ),
                ),
                (
                    "seguro_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimiento Seguro"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculos",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "ordering": ["patente"],
                "unique_together": {("empresa", "patente")},
            },
        ),
        migrations.CreateModel(
            name="Chofer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de RUT inválido. Ejemplo: 12345678-9",
                                regex="^\\d{1,8}-[\\dkK]$",
                            )
                        ],
                        verbose_name="RUT",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre Completo"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "licencia_clase",
                    models.CharField(
                        blank=True,
                        help_text="A1, A2, B, C, D, E, etc.",
                        max_length=10,
                        verbose_name="Clase de Licencia",
                    ),
                ),
                (
                    "licencia_numero",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de Licencia"
                    ),
                ),
                (
                    "licencia_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimiento de Licencia"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choferes",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chofer",
                "verbose_name_plural": "Choferes",
                "ordering": ["nombre"],
                "unique_together": {("empresa", "rut")},
            },
        ),
        migrations.AddField(
            model_name="ordendespacho",
            name="chofer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="despachos",
                to="pedidos.chofer",
                verbose_name="Chofer Asignado",
            ),
        ),
        migrations.AddField(
            model_name="ordendespacho",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="despachos",
                to="pedidos.vehiculo",
                verbose_name="Vehículo Asignado",
            ),
        ),
    ]
