# Generated by Django 4.2.13 on 2025-10-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0014_agregar_config_impresoras"),
        ("pedidos", "0003_remove_ordendespacho_conductor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chofer",
            options={
                "ordering": ["codigo"],
                "verbose_name": "Chofer",
                "verbose_name_plural": "Choferes",
            },
        ),
        migrations.AlterUniqueTogether(
            name="chofer",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="año",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="capacidad_carga",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="capacidad_volumen",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="color",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="marca",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="modelo",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="numero_chasis",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="numero_motor",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="observaciones",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="permiso_circulacion_vencimiento",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="revision_tecnica_vencimiento",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="seguro_vencimiento",
        ),
        migrations.RemoveField(
            model_name="vehiculo",
            name="tipo_vehiculo",
        ),
        migrations.AddField(
            model_name="chofer",
            name="codigo",
            field=models.CharField(
                default="CH001", max_length=20, verbose_name="Código"
            ),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="capacidad",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Capacidad de carga en kilogramos",
                max_digits=10,
                null=True,
                verbose_name="Capacidad (kg)",
            ),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="descripcion",
            field=models.CharField(
                default="Sin descripción",
                help_text="Ej: Camión Toyota Hilux 2020",
                max_length=200,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chofer",
            unique_together={("empresa", "codigo")},
        ),
        migrations.RemoveField(
            model_name="chofer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="chofer",
            name="licencia_clase",
        ),
        migrations.RemoveField(
            model_name="chofer",
            name="licencia_numero",
        ),
        migrations.RemoveField(
            model_name="chofer",
            name="licencia_vencimiento",
        ),
        migrations.RemoveField(
            model_name="chofer",
            name="telefono",
        ),
    ]
