# Generated by Django 4.2.13 on 2025-10-28 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0018_remove_empresa_max_descuento_linea_and_more"),
        ("clientes", "0006_remove_cliente_dias_visitas_and_more"),
        ("ventas", "0022_remove_venta_chofer_remove_venta_vehiculo"),
        ("pedidos", "0005_ruta"),
    ]

    operations = [
        migrations.CreateModel(
            name="HojaRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ruta",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Ruta",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Ruta"
                    ),
                ),
                (
                    "ayudante",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ayudante"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("preparacion", "En Preparación"),
                            ("ruta", "En Ruta"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="preparacion",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "chofer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pedidos.chofer",
                        verbose_name="Chofer",
                    ),
                ),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to=models.Q(
                            ("tipo_documento__in", ["factura", "guia"])
                        ),
                        related_name="hojas_de_ruta",
                        to="ventas.venta",
                        verbose_name="Documentos (Facturas/Guías)",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pedidos.vehiculo",
                        verbose_name="Vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hoja de Ruta",
                "verbose_name_plural": "Hojas de Ruta",
                "ordering": ["-fecha", "-numero_ruta"],
                "permissions": [
                    ("can_view_hojaruta", "Puede ver hojas de ruta"),
                    (
                        "can_change_estado_hojaruta",
                        "Puede cambiar el estado de hojas de ruta",
                    ),
                ],
            },
        ),
        migrations.DeleteModel(
            name="Ruta",
        ),
    ]
