# Generated by Django 4.2.13 on 2025-10-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_hojaruta_delete_ruta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HojaRuta",
        ),
    ]
