# Generated by Django 4.2.13 on 2025-11-02 20:47

from django.db import migrations


def regenerar_numeros_despacho(apps, schema_editor):
    OrdenPedido = apps.get_model('pedidos', 'OrdenPedido')
    OrdenDespacho = apps.get_model('pedidos', 'OrdenDespacho')

    for pedido in OrdenPedido.objects.all():
        despachos = OrdenDespacho.objects.filter(orden_pedido=pedido).order_by('fecha_creacion', 'id')
        for i, despacho in enumerate(despachos):
            nuevo_numero = i + 1
            despacho.numero_despacho = f"DESP-{pedido.id}-{nuevo_numero}"
            despacho.save(update_fields=['numero_despacho'])

class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_delete_hojaruta'),
    ]

    operations = [
        migrations.RunPython(regenerar_numeros_despacho, reverse_code=migrations.RunPython.noop),
    ]
