# Generated by Django 4.2.13 on 2025-11-21 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0023_remove_empresa_max_articulos_factura_laser_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facturacion_electronica", "0010_documentotributarioelectronico_fecha"),
        ("pedidos", "0008_auto_20251102_1747"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ejemplo: RUTA-01, NORTE-01, etc.",
                        max_length=20,
                        verbose_name="Código de Ruta",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ejemplo: Ruta Norte, Ruta Centro, Ruta Sur",
                        max_length=200,
                        verbose_name="Nombre de la Ruta",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de la ruta, zonas que cubre, etc.",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "dias_visita",
                    models.CharField(
                        blank=True,
                        help_text="Ejemplo: Lunes, Miércoles, Viernes",
                        max_length=50,
                        verbose_name="Días de Visita",
                    ),
                ),
                (
                    "orden_visita",
                    models.IntegerField(
                        default=0,
                        help_text="Orden en que se visita esta ruta (1, 2, 3...)",
                        verbose_name="Orden de Visita",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rutas_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutas",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruta",
                "verbose_name_plural": "Rutas",
                "ordering": ["orden_visita", "codigo"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="HojaRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ruta",
                    models.CharField(
                        help_text="Auto-generado: HR-YYYYMMDD-RUTA-XXX",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Hoja de Ruta",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Ruta"
                    ),
                ),
                (
                    "ayudante",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del ayudante si aplica",
                        max_length=200,
                        verbose_name="Ayudante",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_ruta", "En Ruta"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "hora_salida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Salida"
                    ),
                ),
                (
                    "hora_llegada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Llegada"
                    ),
                ),
                (
                    "kilometraje_salida",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kilometraje de Salida"
                    ),
                ),
                (
                    "kilometraje_llegada",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kilometraje de Llegada"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "chofer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hojas_ruta",
                        to="pedidos.chofer",
                        verbose_name="Chofer",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hojas_ruta_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hojas_ruta",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "facturas",
                    models.ManyToManyField(
                        help_text="Facturas incluidas en esta hoja de ruta",
                        related_name="hojas_ruta",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="Facturas",
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hojas_ruta",
                        to="pedidos.ruta",
                        verbose_name="Ruta",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hojas_ruta",
                        to="pedidos.vehiculo",
                        verbose_name="Vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hoja de Ruta",
                "verbose_name_plural": "Hojas de Ruta",
                "ordering": ["-fecha", "-numero_ruta"],
                "unique_together": {("empresa", "numero_ruta")},
            },
        ),
    ]
