# Generated by Django 4.2.13 on 2025-11-21 04:08

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion
import django.utils.timezone


def create_ruta_if_not_exists(apps, schema_editor):
    """Crea la tabla Ruta solo si no existe - solo para SQLite"""
    vendor = schema_editor.connection.vendor
    
    # Solo para SQLite necesitamos crear manualmente
    if vendor == 'sqlite':
        # Verificar si la tabla existe
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='pedidos_ruta'")
            table_exists = cursor.fetchone() is not None
        
        # Solo crear si no existe
        if not table_exists:
            schema_editor.execute("""
                CREATE TABLE pedidos_ruta (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    codigo VARCHAR(20) NOT NULL,
                    nombre VARCHAR(200) NOT NULL,
                    descripcion TEXT,
                    dias_visita VARCHAR(50),
                    orden_visita INTEGER NOT NULL DEFAULT 0,
                    activo BOOLEAN NOT NULL DEFAULT 1,
                    fecha_creacion DATETIME NOT NULL,
                    fecha_modificacion DATETIME NOT NULL,
                    creado_por_id INTEGER,
                    empresa_id BIGINT NOT NULL,
                    FOREIGN KEY (creado_por_id) REFERENCES auth_user (id),
                    FOREIGN KEY (empresa_id) REFERENCES empresas_empresa (id),
                    UNIQUE (empresa_id, codigo)
                )
            """)
            # Solo crear índices si la tabla tiene las columnas
            try:
                schema_editor.execute("CREATE INDEX pedidos_ruta_creado_por_id ON pedidos_ruta (creado_por_id)")
            except:
                pass
            try:
                schema_editor.execute("CREATE INDEX pedidos_ruta_empresa_id ON pedidos_ruta (empresa_id)")
            except:
                pass
    # Para PostgreSQL y otros motores, Django creará la tabla automáticamente con el modelo
    # No necesitamos crear manualmente


def reverse_create_ruta(apps, schema_editor):
    """No hace nada en reverso - dejamos la tabla"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0023_remove_empresa_max_articulos_factura_laser_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facturacion_electronica", "0010_documentotributarioelectronico_fecha"),
        ("pedidos", "0008_auto_20251102_1747"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ruta",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "codigo",
                            models.CharField(
                                help_text="Ejemplo: RUTA-01, NORTE-01, etc.",
                                max_length=20,
                                verbose_name="Código de Ruta",
                            ),
                        ),
                        (
                            "nombre",
                            models.CharField(
                                help_text="Ejemplo: Ruta Norte, Ruta Centro, Ruta Sur",
                                max_length=200,
                                verbose_name="Nombre de la Ruta",
                            ),
                        ),
                        (
                            "descripcion",
                            models.TextField(
                                blank=True,
                                help_text="Descripción detallada de la ruta, zonas que cubre, etc.",
                                verbose_name="Descripción",
                            ),
                        ),
                        (
                            "dias_visita",
                            models.CharField(
                                blank=True,
                                help_text="Ejemplo: Lunes, Miércoles, Viernes",
                                max_length=50,
                                verbose_name="Días de Visita",
                            ),
                        ),
                        (
                            "orden_visita",
                            models.IntegerField(
                                default=0,
                                help_text="Orden en que se visita esta ruta (1, 2, 3...)",
                                verbose_name="Orden de Visita",
                            ),
                        ),
                        ("activo", models.BooleanField(default=True, verbose_name="Activa")),
                        (
                            "fecha_creacion",
                            models.DateTimeField(
                                auto_now_add=True, verbose_name="Fecha de Creación"
                            ),
                        ),
                        (
                            "fecha_modificacion",
                            models.DateTimeField(
                                auto_now=True, verbose_name="Fecha de Modificación"
                            ),
                        ),
                        (
                            "creado_por",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="rutas_creadas",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Creado por",
                            ),
                        ),
                        (
                            "empresa",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="rutas",
                                to="empresas.empresa",
                                verbose_name="Empresa",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Ruta",
                        "verbose_name_plural": "Rutas",
                        "ordering": ["orden_visita", "codigo"],
                        "unique_together": {("empresa", "codigo")},
                    },
                ),
        migrations.CreateModel(
            name="HojaRuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ruta",
                    models.CharField(
                        help_text="Auto-generado: HR-YYYYMMDD-RUTA-XXX",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Hoja de Ruta",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Ruta"
                    ),
                ),
                (
                    "ayudante",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del ayudante si aplica",
                        max_length=200,
                        verbose_name="Ayudante",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_ruta", "En Ruta"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "hora_salida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Salida"
                    ),
                ),
                (
                    "hora_llegada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Llegada"
                    ),
                ),
                (
                    "kilometraje_salida",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kilometraje de Salida"
                    ),
                ),
                (
                    "kilometraje_llegada",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kilometraje de Llegada"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "chofer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hojas_ruta",
                        to="pedidos.chofer",
                        verbose_name="Chofer",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hojas_ruta_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hojas_ruta",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "facturas",
                    models.ManyToManyField(
                        help_text="Facturas incluidas en esta hoja de ruta",
                        related_name="hojas_ruta",
                        to="facturacion_electronica.documentotributarioelectronico",
                        verbose_name="Facturas",
                    ),
                ),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hojas_ruta",
                        to="pedidos.ruta",
                        verbose_name="Ruta",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hojas_ruta",
                        to="pedidos.vehiculo",
                        verbose_name="Vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hoja de Ruta",
                "verbose_name_plural": "Hojas de Ruta",
                "ordering": ["-fecha", "-numero_ruta"],
                "unique_together": {("empresa", "numero_ruta")},
            },
        ),
    ]
