# Generated by Django 4.2.13 on 2025-11-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0010_add_ruta_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="chofer",
            name="tipo",
            field=models.CharField(
                choices=[("chofer", "Chofer"), ("acompanante", "Acompañante")],
                default="chofer",
                help_text="Indica si es chofer o acompañante",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddField(
            model_name="hojaruta",
            name="acompanante",
            field=models.ForeignKey(
                blank=True,
                help_text="Acompañante asignado a esta hoja de ruta",
                limit_choices_to={"activo": True, "tipo": "acompanante"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hojas_ruta_como_acompanante",
                to="pedidos.chofer",
                verbose_name="Acompañante",
            ),
        ),
        migrations.AddField(
            model_name="ruta",
            name="acompanante",
            field=models.ForeignKey(
                blank=True,
                help_text="Acompañante asignado a esta ruta (opcional)",
                limit_choices_to={"activo": True, "tipo": "acompanante"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rutas_como_acompanante",
                to="pedidos.chofer",
                verbose_name="Acompañante",
            ),
        ),
        migrations.AddField(
            model_name="ruta",
            name="chofer",
            field=models.ForeignKey(
                blank=True,
                help_text="Chofer asignado a esta ruta",
                limit_choices_to={"activo": True, "tipo": "chofer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rutas_como_chofer",
                to="pedidos.chofer",
                verbose_name="Chofer",
            ),
        ),
        migrations.AddField(
            model_name="ruta",
            name="vehiculo",
            field=models.ForeignKey(
                blank=True,
                help_text="Vehículo asignado a esta ruta",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rutas",
                to="pedidos.vehiculo",
                verbose_name="Vehículo",
            ),
        ),
        migrations.AlterField(
            model_name="hojaruta",
            name="ayudante",
            field=models.CharField(
                blank=True,
                help_text="Nombre del ayudante si aplica (campo adicional)",
                max_length=200,
                verbose_name="Ayudante",
            ),
        ),
    ]
