# Generated by Django 4.2.13 on 2025-11-22 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0011_add_ruta_vehiculo_chofer_acompanante"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="chofer",
            field=models.ForeignKey(
                blank=True,
                help_text="Chofer asignado por defecto a este vehículo",
                limit_choices_to={"activo": True, "tipo": "chofer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehiculos_asignados",
                to="pedidos.chofer",
                verbose_name="Chofer Asignado",
            ),
        ),
    ]
