# Generated by Django 4.2.13 on 2026-03-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0012_add_chofer_to_vehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordendespacho",
            name="tipo_traslado",
            field=models.CharField(
                choices=[
                    ("1", "Venta"),
                    ("2", "Venta por efectuar"),
                    ("3", "Consignación"),
                    ("4", "Devolución"),
                    ("5", "Traslado interno"),
                    ("6", "Transformación"),
                    ("7", "Entrega gratuita"),
                    ("8", "Otros"),
                ],
                default="1",
                max_length=1,
                verbose_name="Tipo de Traslado (IndTraslado)",
            ),
        ),
    ]
