# Generated by Django 5.2.7 on 2026-06-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0028_plansaas_empresa_auto_suspender_and_more'),
        ('pedidos', '0013_ordendespacho_tipo_traslado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaruta',
            name='numero_ruta',
            field=models.CharField(help_text='Auto-generado: HR-YYYYMMDD-RUTA-XXX', max_length=50, verbose_name='Número de Hoja de Ruta'),
        ),
        migrations.AlterField(
            model_name='ordenpedido',
            name='numero_pedido',
            field=models.CharField(max_length=20, verbose_name='Número de Pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='ordenpedido',
            unique_together={('empresa', 'numero_pedido')},
        ),
    ]
