# Generated by Django 5.2.7 on 2026-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_alter_hojaruta_numero_ruta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordenpedido',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='numero_ruta',
            field=models.CharField(help_text='Auto-generado: HR-YYYYMMDD-RUTA-XXX', max_length=50, unique=True, verbose_name='Número de Hoja de Ruta'),
        ),
        migrations.AlterField(
            model_name='ordenpedido',
            name='numero_pedido',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Pedido'),
        ),
    ]
