# Generated by Django 5.2.6 on 2025-09-26 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockarticulo",
            name="articulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_articulos",
                to="articulos.articulo",
                verbose_name="Artículo",
            ),
        ),
    ]
