# Generated by Django 5.2.6 on 2025-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0002_alter_stockarticulo_articulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="tipo_articulo",
            field=models.CharField(
                choices=[
                    ("producto_venta", "Producto de Venta"),
                    ("insumo", "Insumo"),
                    ("ambos", "Producto e Insumo"),
                ],
                default="producto_venta",
                max_length=20,
                verbose_name="Tipo de Artículo",
            ),
        ),
    ]
