# Generated by Django 5.2.6 on 2025-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0003_articulo_tipo_articulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="codigo_barras",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Código de Barras",
            ),
        ),
    ]
