# Generated by Django 5.2.6 on 2025-09-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0004_articulo_codigo_barras"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articulos/logos/",
                verbose_name="Logo del Artículo",
            ),
        ),
    ]
