# Generated by Django 5.2.6 on 2025-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0005_articulo_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="impuesto_especifico",
            field=models.CharField(
                default="0.00", max_length=50, verbose_name="Impuesto Específico"
            ),
        ),
    ]
