# Generated by Django 5.1.5 on 2025-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0006_articulo_impuesto_especifico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="impuesto_especifico",
            field=models.CharField(
                blank=True,
                default="0.00",
                max_length=50,
                null=True,
                verbose_name="Impuesto Específico",
            ),
        ),
    ]
