# Generated by Django 5.1.5 on 2025-10-09 23:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0007_alter_articulo_impuesto_especifico"),
        ("empresas", "0011_empresa_oficina_sii"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre de la Lista"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "es_predeterminada",
                    models.BooleanField(
                        default=False, verbose_name="Lista Predeterminada"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Precios",
                "verbose_name_plural": "Listas de Precios",
                "ordering": ["-es_predeterminada", "nombre"],
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="PrecioArticulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Precio",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios",
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "lista_precio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios",
                        to="articulos.listaprecio",
                        verbose_name="Lista de Precios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de Artículo",
                "verbose_name_plural": "Precios de Artículos",
                "ordering": ["lista_precio", "articulo"],
                "unique_together": {("articulo", "lista_precio")},
            },
        ),
    ]
