# Generated by Django 5.1.5 on 2025-10-11 18:22

from django.db import migrations, models


def migrar_datos_categoria(apps, schema_editor):
    """
    Migrar datos de categorías:
    - codigo = valor actual de nombre
    - nombre = valor actual de descripcion (si existe)
    """
    CategoriaArticulo = apps.get_model('articulos', 'CategoriaArticulo')
    
    for categoria in CategoriaArticulo.objects.all():
        # Guardar el valor actual de nombre en codigo
        categoria.codigo = categoria.nombre
        
        # Si hay descripción, moverla a nombre
        if categoria.descripcion and categoria.descripcion.strip():
            categoria.nombre = categoria.descripcion.strip()
        
        categoria.save()


def revertir_migracion(apps, schema_editor):
    """Revertir la migración moviendo codigo de vuelta a nombre"""
    CategoriaArticulo = apps.get_model('articulos', 'CategoriaArticulo')
    
    for categoria in CategoriaArticulo.objects.all():
        if categoria.codigo:
            categoria.nombre = categoria.codigo
            categoria.save()


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0008_listaprecio_precioarticulo"),
        ("empresas", "0011_empresa_oficina_sii"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categoriaarticulo",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="categoriaarticulo",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, verbose_name="Código"),
        ),
        migrations.RunPython(migrar_datos_categoria, revertir_migracion),
        migrations.AlterUniqueTogether(
            name="categoriaarticulo",
            unique_together={("empresa", "codigo")},
        ),
    ]
