# Generated by Django 5.1.5 on 2025-10-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0009_alter_categoriaarticulo_unique_together_and_more"),
        ("empresas", "0011_empresa_oficina_sii"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="codigo",
            field=models.CharField(max_length=50, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="codigo_barras",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código de Barras"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articulo",
            unique_together={("empresa", "codigo"), ("empresa", "codigo_barras")},
        ),
    ]
