# Generated by Django 5.1.5 on 2025-10-17 01:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articulos",
            "0010_alter_articulo_codigo_alter_articulo_codigo_barras_and_more",
        ),
        ("proveedores", "0002_alter_proveedor_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomologacionCodigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_proveedor",
                    models.CharField(
                        max_length=100, verbose_name="Código del Proveedor"
                    ),
                ),
                (
                    "descripcion_proveedor",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Descripción del Proveedor",
                    ),
                ),
                (
                    "precio_compra",
                    models.IntegerField(
                        default=0,
                        help_text="Último precio de compra a este proveedor",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio de Compra",
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False, verbose_name="Proveedor Principal"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homologaciones",
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homologación de Código",
                "verbose_name_plural": "Homologaciones de Códigos",
                "ordering": ["-es_principal", "proveedor__nombre"],
                "unique_together": {("articulo", "proveedor", "codigo_proveedor")},
            },
        ),
    ]
