# Generated by Django 5.1.5 on 2025-10-17 02:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0011_homologacioncodigo"),
        ("empresas", "0011_empresa_oficina_sii"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitOferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Código del Kit"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Kit"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kits/",
                        verbose_name="Imagen del Kit",
                    ),
                ),
                (
                    "precio_kit",
                    models.IntegerField(
                        default=0,
                        help_text="Precio especial del kit completo",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio del Kit",
                    ),
                ),
                (
                    "descuento_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de descuento aplicado",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Descuento %",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True,
                        help_text="Fecha desde la cual el kit está disponible",
                        null=True,
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Fecha hasta la cual el kit está disponible",
                        null=True,
                        verbose_name="Fecha de Fin",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "destacado",
                    models.BooleanField(
                        default=False,
                        help_text="Mostrar el kit en posición destacada",
                        verbose_name="Destacado",
                    ),
                ),
                (
                    "stock_disponible",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad de kits disponibles",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock Disponible",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kit de Oferta",
                "verbose_name_plural": "Kits de Ofertas",
                "ordering": ["-destacado", "-fecha_creacion"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="KitOfertaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de visualización del item",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Observaciones"
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="articulos.kitoferta",
                        verbose_name="Kit de Oferta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Kit",
                "verbose_name_plural": "Items de Kit",
                "ordering": ["orden", "id"],
                "unique_together": {("kit", "articulo")},
            },
        ),
    ]
