# Generated by Django 5.1.5 on 2025-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0012_kitoferta_kitofertaitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="dias_vencimiento",
            field=models.IntegerField(
                blank=True,
                help_text="Días de vida útil del producto desde su producción",
                null=True,
                verbose_name="Días hasta Vencimiento",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="requiere_lote",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el producto requiere control de lotes",
                verbose_name="Requiere Número de Lote",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="temperatura_almacenamiento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Temperatura requerida para almacenar el producto",
                max_digits=5,
                null=True,
                verbose_name="Temperatura de Almacenamiento (°C)",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="tiene_variantes",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el producto tiene variantes (tallas, colores, etc.)",
                verbose_name="Tiene Variantes",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="tiene_vencimiento",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el producto tiene fecha de vencimiento",
                verbose_name="Tiene Fecha de Vencimiento",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="tipo_produccion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("textil", "Textil"),
                    ("carnico", "Cárnico"),
                    ("panaderia", "Panadería"),
                    ("quimico", "Químico"),
                    ("otro", "Otro"),
                ],
                help_text="Industria a la que pertenece este producto",
                max_length=20,
                null=True,
                verbose_name="Tipo de Producción",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="unidad_produccion",
            field=models.CharField(
                choices=[
                    ("unidad", "Unidades"),
                    ("kg", "Kilogramos"),
                    ("gramos", "Gramos"),
                    ("litros", "Litros"),
                    ("ml", "Mililitros"),
                    ("metros", "Metros"),
                    ("cm", "Centímetros"),
                ],
                default="unidad",
                help_text="Unidad en la que se produce este artículo",
                max_length=20,
                verbose_name="Unidad de Producción",
            ),
        ),
    ]
