# Generated by Django 5.1.5 on 2025-10-17 15:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0013_articulo_dias_vencimiento_articulo_requiere_lote_and_more"),
        ("empresas", "0011_empresa_oficina_sii"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecetaProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, verbose_name="Código")),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Receta"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "cantidad_producir",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad que produce esta receta",
                        max_digits=10,
                        verbose_name="Cantidad a Producir",
                    ),
                ),
                (
                    "merma_estimada",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Porcentaje de merma estimado en el proceso",
                        max_digits=5,
                        verbose_name="Merma Estimada (%)",
                    ),
                ),
                (
                    "tiempo_estimado",
                    models.IntegerField(
                        help_text="Tiempo estimado de producción en minutos",
                        verbose_name="Tiempo Estimado (minutos)",
                    ),
                ),
                (
                    "temperatura_proceso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Temperatura requerida para el proceso (cárnico/químico)",
                        max_digits=5,
                        null=True,
                        verbose_name="Temperatura de Proceso (°C)",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "producto_final",
                    models.ForeignKey(
                        limit_choices_to={
                            "tipo_articulo__in": ["producto_venta", "ambos"]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas",
                        to="articulos.articulo",
                        verbose_name="Producto Final",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta de Producción",
                "verbose_name_plural": "Recetas de Producción",
                "ordering": ["codigo"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="OrdenProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_orden",
                    models.CharField(max_length=50, verbose_name="Número de Orden"),
                ),
                (
                    "cantidad_planificada",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cantidad Planificada",
                    ),
                ),
                (
                    "cantidad_producida",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Cantidad Producida",
                    ),
                ),
                (
                    "merma_real",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Merma Real",
                    ),
                ),
                (
                    "fecha_planificada",
                    models.DateField(verbose_name="Fecha Planificada"),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_proceso", "En Proceso"),
                            ("terminada", "Terminada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Responsable"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "lote_produccion",
                    models.CharField(
                        blank=True,
                        help_text="Número de lote para trazabilidad (cárnico)",
                        max_length=50,
                        verbose_name="Lote de Producción",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de vencimiento del lote producido (cárnico)",
                        null=True,
                        verbose_name="Fecha de Vencimiento",
                    ),
                ),
                (
                    "temperatura_proceso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Temperatura de Proceso (°C)",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="articulos.recetaproduccion",
                        verbose_name="Receta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Producción",
                "verbose_name_plural": "Órdenes de Producción",
                "ordering": ["-fecha_planificada", "-numero_orden"],
                "unique_together": {("empresa", "numero_orden")},
            },
        ),
        migrations.CreateModel(
            name="InsumoReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cantidad Necesaria",
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Orden en el que se agrega el insumo",
                        verbose_name="Orden",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre este insumo en la receta",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        limit_choices_to={"tipo_articulo__in": ["insumo", "ambos"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="articulos.articulo",
                        verbose_name="Insumo",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insumos",
                        to="articulos.recetaproduccion",
                        verbose_name="Receta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insumo de Receta",
                "verbose_name_plural": "Insumos de Receta",
                "ordering": ["orden", "id"],
                "unique_together": {("receta", "articulo")},
            },
        ),
    ]
