# Generated by Django 5.1.5 on 2025-10-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0014_recetaproduccion_ordenproduccion_insumoreceta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="tipo_articulo",
            field=models.CharField(
                choices=[
                    ("producto_venta", "Producto de Venta"),
                    ("insumo", "Insumo"),
                    ("produccion", "Artículo de Producción"),
                    ("ambos", "Producto e Insumo"),
                ],
                default="producto_venta",
                max_length=20,
                verbose_name="Tipo de Artículo",
            ),
        ),
    ]
