# Generated by Django 5.1.5 on 2025-10-18 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0015_alter_articulo_tipo_articulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="meses_garantia",
            field=models.IntegerField(
                blank=True,
                help_text="Período de garantía del producto fabricado",
                null=True,
                verbose_name="Meses de Garantía",
            ),
        ),
        migrations.AlterField(
            model_name="recetaproduccion",
            name="producto_final",
            field=models.ForeignKey(
                limit_choices_to={"tipo_articulo": "produccion"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recetas",
                to="articulos.articulo",
                verbose_name="Producto Final",
            ),
        ),
    ]
