# Generated by Django 5.2.7 on 2025-10-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0016_ordenproduccion_meses_garantia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaarticulo",
            name="codigo",
            field=models.CharField(max_length=50, verbose_name="Código"),
        ),
    ]
