# Generated by Django 4.2.13 on 2025-10-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0017_alter_categoriaarticulo_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="descripcion_oferta",
            field=models.TextField(
                blank=True,
                help_text="Descripción o mensaje promocional de la oferta",
                verbose_name="Descripción de la Oferta",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="en_oferta",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el artículo está en oferta/promoción",
                verbose_name="En Oferta",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="fecha_fin_oferta",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que finaliza la oferta",
                null=True,
                verbose_name="Fin de Oferta",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="fecha_inicio_oferta",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que inicia la oferta",
                null=True,
                verbose_name="Inicio de Oferta",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="porcentaje_descuento_oferta",
            field=models.CharField(
                blank=True,
                default="0.00",
                help_text="Porcentaje de descuento sobre el precio normal",
                max_length=50,
                null=True,
                verbose_name="Descuento de Oferta (%)",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="precio_oferta",
            field=models.CharField(
                blank=True,
                default="0.00",
                help_text="Precio especial mientras la oferta esté activa",
                max_length=50,
                null=True,
                verbose_name="Precio de Oferta",
            ),
        ),
    ]
