# Generated by Django 4.2.13 on 2026-07-04 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0029_empresa_venta_movil_permite_sin_stock"),
        ("articulos", "0018_agregar_sistema_ofertas"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialCambioPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operacion_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID de Operacion",
                    ),
                ),
                (
                    "articulo_codigo",
                    models.CharField(max_length=50, verbose_name="Codigo Articulo"),
                ),
                (
                    "articulo_nombre",
                    models.CharField(max_length=200, verbose_name="Nombre Articulo"),
                ),
                (
                    "categoria_nombre",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nombre Familia"
                    ),
                ),
                (
                    "alcance",
                    models.CharField(
                        choices=[
                            ("familia", "Familia"),
                            ("seleccionados", "Productos seleccionados"),
                        ],
                        max_length=20,
                        verbose_name="Alcance",
                    ),
                ),
                (
                    "base_calculo",
                    models.CharField(
                        choices=[
                            ("neto", "Precio neto"),
                            ("final", "Precio final con impuestos"),
                        ],
                        max_length=10,
                        verbose_name="Base de Calculo",
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Porcentaje Aplicado",
                    ),
                ),
                (
                    "precio_neto_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Neto Anterior"
                    ),
                ),
                (
                    "iva_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="IVA Anterior"
                    ),
                ),
                (
                    "impuesto_especifico_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Impuesto Especifico Anterior",
                    ),
                ),
                (
                    "precio_final_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Final Anterior"
                    ),
                ),
                (
                    "precio_neto_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Neto Nuevo"
                    ),
                ),
                (
                    "iva_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="IVA Nuevo"
                    ),
                ),
                (
                    "impuesto_especifico_nuevo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Impuesto Especifico Nuevo",
                    ),
                ),
                (
                    "precio_final_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Final Nuevo"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_cambios_precio",
                        to="articulos.articulo",
                        verbose_name="Articulo",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articulos.categoriaarticulo",
                        verbose_name="Familia",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Cambio de Precio",
                "verbose_name_plural": "Historial de Cambios de Precio",
                "ordering": ["-fecha_creacion", "-id"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "fecha_creacion"],
                        name="articulos_h_empresa_4f33ba_idx",
                    ),
                    models.Index(
                        fields=["articulo", "fecha_creacion"],
                        name="articulos_h_articul_d6dfc5_idx",
                    ),
                    models.Index(
                        fields=["operacion_id"], name="articulos_h_operaci_8cb73d_idx"
                    ),
                ],
            },
        ),
    ]
