# Generated by Django 4.2.7 on 2025-10-04 01:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documentos", "0005_alter_documentocompra_descuentos_totales_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proveedores", "0002_alter_proveedor_unique_together_and_more"),
        ("empresas", "0005_remove_configuracionempresa_formato_boletas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaCorrienteProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Total",
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "saldo_vencido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Vencido",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_corrientes_proveedores",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_corrientes",
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Corriente Proveedor",
                "verbose_name_plural": "Cuentas Corrientes Proveedores",
                "ordering": ["proveedor__nombre"],
                "unique_together": {("empresa", "proveedor")},
            },
        ),
        migrations.CreateModel(
            name="MovimientoCuentaCorriente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[("debe", "Debe"), ("haber", "Haber")],
                        max_length=10,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "saldo_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Anterior"
                    ),
                ),
                (
                    "saldo_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Nuevo"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmado", "Confirmado"),
                            ("anulado", "Anulado"),
                        ],
                        default="confirmado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_movimiento",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Movimiento",
                    ),
                ),
                (
                    "cuenta_corriente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="tesoreria.cuentacorrienteproveedor",
                        verbose_name="Cuenta Corriente",
                    ),
                ),
                (
                    "documento_compra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_cuenta_corriente",
                        to="documentos.documentocompra",
                        verbose_name="Documento de Compra",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Cuenta Corriente",
                "verbose_name_plural": "Movimientos de Cuenta Corriente",
                "ordering": ["-fecha_movimiento"],
            },
        ),
    ]
