# Generated by Django 5.1.5 on 2025-10-08 02:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_alter_cliente_sitio_web"),
        ("empresas", "0009_remove_empresa_alerta_folios_minimos"),
        ("tesoreria", "0001_initial"),
        ("ventas", "0007_venta_estado_cotizacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaCorrienteCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Total",
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "saldo_vencido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Vencido",
                    ),
                ),
                (
                    "limite_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Límite de Crédito",
                    ),
                ),
                (
                    "dias_credito",
                    models.IntegerField(default=30, verbose_name="Días de Crédito"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_corrientes",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_corrientes_clientes",
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Corriente Cliente",
                "verbose_name_plural": "Cuentas Corrientes Clientes",
                "ordering": ["cliente__nombre"],
                "unique_together": {("empresa", "cliente")},
            },
        ),
        migrations.CreateModel(
            name="MovimientoCuentaCorrienteCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[("debe", "Debe"), ("haber", "Haber")],
                        max_length=10,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "saldo_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Anterior"
                    ),
                ),
                (
                    "saldo_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Saldo Nuevo"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmado", "Confirmado"),
                            ("anulado", "Anulado"),
                        ],
                        default="confirmado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_movimiento",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Movimiento",
                    ),
                ),
                (
                    "cuenta_corriente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="tesoreria.cuentacorrientecliente",
                        verbose_name="Cuenta Corriente",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_cuenta_corriente",
                        to="ventas.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Cuenta Corriente de Cliente",
                "verbose_name_plural": "Movimientos de Cuenta Corriente de Clientes",
                "ordering": ["-fecha_movimiento"],
            },
        ),
    ]
