# Generated by Django 5.1.5 on 2025-10-09 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_alter_cliente_sitio_web"),
        ("empresas", "0011_empresa_oficina_sii"),
        ("tesoreria", "0002_cuentacorrientecliente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("factura", "Factura"),
                            ("boleta", "Boleta"),
                            ("nota_credito", "Nota de Crédito"),
                            ("nota_debito", "Nota de Débito"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=50, verbose_name="Número de Documento"),
                ),
                ("fecha_emision", models.DateField(verbose_name="Fecha de Emisión")),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                ("total", models.IntegerField(default=0, verbose_name="Total")),
                (
                    "monto_pagado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Monto Pagado",
                    ),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("parcial", "Parcial"),
                            ("pagado", "Pagado"),
                            ("vencido", "Vencido"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado de Pago",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_cuenta_corriente",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_cliente_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Cliente",
                "verbose_name_plural": "Documentos de Clientes",
                "ordering": ["-fecha_creacion"],
                "unique_together": {("empresa", "numero_documento", "tipo_documento")},
            },
        ),
    ]
