# Generated by Django 5.1.5 on 2025-10-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermisoInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de Informe",
                "verbose_name_plural": "Permisos de Informes",
                "permissions": (
                    ("ver_informe_ventas", "Puede ver Informe de Ventas"),
                    ("ver_informe_compras", "Puede ver Informe de Compras"),
                    ("ver_informe_inventario", "Puede ver Informe de Inventario"),
                    ("ver_informe_clientes", "Puede ver Informe de Clientes"),
                    ("ver_informe_proveedores", "Puede ver Informe de Proveedores"),
                    ("ver_informe_caja", "Puede ver Informe de Caja"),
                    ("ver_informe_tesoreria", "Puede ver Informe de Tesorería"),
                    ("ver_informe_estadisticas", "Puede ver Informe de Estadísticas"),
                    ("ver_informe_rentabilidad", "Puede ver Informe de Rentabilidad"),
                    ("ver_informe_stock", "Puede ver Informe de Stock"),
                    ("exportar_informes", "Puede exportar Informes a Excel/PDF"),
                ),
                "managed": False,
            },
        ),
    ]
