# Generated by Django 5.2.7 on 2025-10-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PermisoInforme",
        ),
    ]
