# Generated by Django 5.1.5 on 2025-10-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0011_empresa_oficina_sii"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="empresas.sucursal",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("vendedor", "Vendedor"),
                    ("cajero", "Cajero"),
                ],
                default="vendedor",
                max_length=20,
                verbose_name="Tipo de Usuario",
            ),
        ),
    ]
