# Generated by Django 5.2.6 on 2025-09-26 04:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ventas", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, verbose_name="Código del Cliente"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Cliente"),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razón Social"
                    ),
                ),
                (
                    "tipo_cliente",
                    models.CharField(
                        choices=[
                            ("consumidor_final", "Consumidor Final"),
                            ("contribuyente", "Contribuyente"),
                            ("exento", "Exento de IVA"),
                            ("extranjero", "Extranjero"),
                        ],
                        default="consumidor_final",
                        max_length=20,
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El RUT debe tener el formato XX.XXX.XXX-X",
                                regex="^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$",
                            )
                        ],
                        verbose_name="RUT",
                    ),
                ),
                (
                    "giro",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Giro Comercial"
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                ("comuna", models.CharField(max_length=100, verbose_name="Comuna")),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                ("region", models.CharField(max_length=100, verbose_name="Región")),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "sitio_web",
                    models.URLField(blank=True, null=True, verbose_name="Sitio Web"),
                ),
                (
                    "limite_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Límite de Crédito",
                    ),
                ),
                (
                    "plazo_pago",
                    models.IntegerField(
                        default=30, verbose_name="Plazo de Pago (días)"
                    ),
                ),
                (
                    "descuento_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Descuento por Defecto (%)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                            ("moroso", "Moroso"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_alta",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Alta"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="ContactoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Contacto"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                (
                    "tipo_contacto",
                    models.CharField(
                        choices=[
                            ("principal", "Contacto Principal"),
                            ("comercial", "Contacto Comercial"),
                            ("administrativo", "Contacto Administrativo"),
                            ("tecnico", "Contacto Técnico"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "celular",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "es_contacto_principal",
                    models.BooleanField(
                        default=False, verbose_name="Es Contacto Principal"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto de Cliente",
                "verbose_name_plural": "Contactos de Clientes",
                "ordering": ["cliente", "tipo_contacto", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CuentaCorrienteCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Movimiento",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("venta", "Venta"),
                            ("pago", "Pago"),
                            ("nota_credito", "Nota de Crédito"),
                            ("nota_debito", "Nota de Débito"),
                            ("ajuste", "Ajuste"),
                            ("devolucion", "Devolución"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Monto"
                    ),
                ),
                (
                    "saldo_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Saldo Anterior"
                    ),
                ),
                (
                    "saldo_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Saldo Nuevo"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_cuenta",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Cuenta Corriente de Cliente",
                "verbose_name_plural": "Movimientos de Cuenta Corriente de Clientes",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HistorialPreciosCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Precio Anterior"
                    ),
                ),
                (
                    "precio_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Precio Nuevo"
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del Cambio"
                    ),
                ),
                (
                    "motivo_cambio",
                    models.TextField(blank=True, verbose_name="Motivo del Cambio"),
                ),
                (
                    "cambiado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_precios",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Precios por Cliente",
                "verbose_name_plural": "Historial de Precios por Cliente",
                "ordering": ["-fecha_cambio"],
            },
        ),
    ]
