# Generated by Django 5.2.6 on 2025-09-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together={("empresa", "rut")},
        ),
        migrations.AlterField(
            model_name="cliente",
            name="rut",
            field=models.CharField(
                blank=True,
                help_text="Formato: 12.345.678-9 o 12345678-9",
                max_length=12,
                null=True,
                verbose_name="RUT",
            ),
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="razon_social",
        ),
    ]
