# Generated by Django 5.2.6 on 2025-09-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_alter_cliente_unique_together_alter_cliente_rut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="sitio_web",
            field=models.CharField(
                blank=True,
                help_text="Formato: www.ejemplo.cl o https://www.ejemplo.cl",
                max_length=200,
                null=True,
                verbose_name="Sitio Web",
            ),
        ),
    ]
