# Generated by Django 5.1.5 on 2025-10-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_alter_cliente_sitio_web"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="region",
            field=models.CharField(blank=True, max_length=100, verbose_name="Región"),
        ),
    ]
