# Generated by Django 4.2.13 on 2025-10-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_ruta"),
        ("clientes", "0004_alter_cliente_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="dias_visitas",
            field=models.CharField(
                blank=True,
                help_text="Ejemplo: Lunes, Miércoles, Viernes",
                max_length=200,
                verbose_name="Días de Visitas",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="ruta_asignada",
            field=models.ForeignKey(
                blank=True,
                help_text="Ruta de despacho asignada al cliente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes",
                to="pedidos.ruta",
                verbose_name="Ruta Asignada",
            ),
        ),
    ]
