# Generated by Django 4.2.13 on 2025-10-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_cliente_dias_visitas_cliente_ruta_asignada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="dias_visitas",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="ruta_asignada",
        ),
    ]
