# Generated by Django 4.2.13 on 2025-11-21 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0009_ruta_hojaruta"),
        ("clientes", "0006_remove_cliente_dias_visitas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ruta",
            field=models.ForeignKey(
                blank=True,
                help_text="Ruta asignada para el despacho de productos a este cliente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes",
                to="pedidos.ruta",
                verbose_name="Ruta de Despacho",
            ),
        ),
    ]
