# Generated by Django 4.2.13 on 2026-02-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0032_dispositivomovil"),
        ("clientes", "0007_cliente_ruta"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendedor responsable de este cliente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_asignados",
                to="ventas.vendedor",
                verbose_name="Vendedor Asignado",
            ),
        ),
    ]
