# Generated by Django 5.1.5 on 2025-10-06 20:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bodegas", "0002_remove_bodega_capacidad_maxima_and_more"),
        ("empresas", "0006_configuracionempresa_formato_orden_compra_and_more"),
        ("ventas", "0007_venta_estado_cotizacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=10, verbose_name="Número de Caja"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre de la Caja"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "bodega",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bodega desde donde se descontará el stock",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bodegas.bodega",
                        verbose_name="Bodega",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "estacion_trabajo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.estaciontrabajo",
                        verbose_name="Estación de Trabajo",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caja",
                "verbose_name_plural": "Cajas",
                "ordering": ["numero"],
                "unique_together": {("empresa", "numero")},
            },
        ),
        migrations.CreateModel(
            name="AperturaCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha Apertura"
                    ),
                ),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Cierre"
                    ),
                ),
                (
                    "monto_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto Inicial",
                    ),
                ),
                (
                    "monto_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto Final",
                    ),
                ),
                (
                    "total_ventas_efectivo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Ventas Efectivo",
                    ),
                ),
                (
                    "total_ventas_tarjeta",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Ventas Tarjeta",
                    ),
                ),
                (
                    "total_ventas_transferencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Ventas Transferencia",
                    ),
                ),
                (
                    "total_ventas_cheque",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Ventas Cheque",
                    ),
                ),
                (
                    "total_ventas_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Ventas Crédito",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("abierta", "Abierta"), ("cerrada", "Cerrada")],
                        default="abierta",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones_apertura",
                    models.TextField(blank=True, verbose_name="Observaciones Apertura"),
                ),
                (
                    "observaciones_cierre",
                    models.TextField(blank=True, verbose_name="Observaciones Cierre"),
                ),
                (
                    "usuario_apertura",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aperturas_caja",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Apertura",
                    ),
                ),
                (
                    "usuario_cierre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cierres_caja",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Cierre",
                    ),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aperturascaja",
                        to="caja.caja",
                        verbose_name="Caja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apertura de Caja",
                "verbose_name_plural": "Aperturas de Caja",
                "ordering": ["-fecha_apertura"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("venta", "Venta"),
                            ("devolucion", "Devolución"),
                            ("retiro", "Retiro"),
                            ("ingreso", "Ingreso"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "numero_cheque",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de Cheque"
                    ),
                ),
                (
                    "banco",
                    models.CharField(blank=True, max_length=100, verbose_name="Banco"),
                ),
                (
                    "fecha_cheque",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del Cheque"
                    ),
                ),
                (
                    "apertura_caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="caja.aperturacaja",
                        verbose_name="Apertura de Caja",
                    ),
                ),
                (
                    "forma_pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.formapago",
                        verbose_name="Forma de Pago",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ventas.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Caja",
                "verbose_name_plural": "Movimientos de Caja",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="VentaProcesada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_proceso",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Proceso"
                    ),
                ),
                (
                    "monto_recibido",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto Recibido",
                    ),
                ),
                (
                    "monto_cambio",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto de Cambio",
                    ),
                ),
                (
                    "stock_descontado",
                    models.BooleanField(default=False, verbose_name="Stock Descontado"),
                ),
                (
                    "cuenta_corriente_actualizada",
                    models.BooleanField(
                        default=False, verbose_name="Cuenta Corriente Actualizada"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "apertura_caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caja.aperturacaja",
                        verbose_name="Apertura de Caja",
                    ),
                ),
                (
                    "movimiento_caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caja.movimientocaja",
                        verbose_name="Movimiento de Caja",
                    ),
                ),
                (
                    "usuario_proceso",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que Procesó",
                    ),
                ),
                (
                    "venta_final",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venta_final",
                        to="ventas.venta",
                        verbose_name="Venta Final (Documento Tributario)",
                    ),
                ),
                (
                    "venta_preventa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venta_preventa",
                        to="ventas.venta",
                        verbose_name="Preventa (Ticket)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta Procesada",
                "verbose_name_plural": "Ventas Procesadas",
                "ordering": ["-fecha_proceso"],
            },
        ),
    ]
