# Generated by Django 5.1.5 on 2025-10-08 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0001_initial"),
        ("facturacion_electronica", "0002_configuracionalertafolios"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventaprocesada",
            name="dte_generado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facturacion_electronica.documentotributarioelectronico",
                verbose_name="DTE Generado",
            ),
        ),
    ]
