# Generated by Django 5.1.5 on 2025-10-19 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0002_ventaprocesada_dte_generado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventaprocesada",
            name="movimiento_caja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caja.movimientocaja",
                verbose_name="Movimiento de Caja",
            ),
        ),
    ]
