# Generated by Django 5.2.7 on 2026-06-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_ventaprocesada_movimiento_caja'),
        ('ventas', '0038_ventadetalle_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_raw', models.TextField(verbose_name='Comandos ESC/POS RAW')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('impreso', 'Impreso'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, verbose_name='Log de Error')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.caja', verbose_name='Caja Destino')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Trabajo de Impresión',
                'verbose_name_plural': 'Cola de Impresión',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
