# Generated by Django 5.2.7 on 2026-06-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_colaimpresion'),
        ('empresas', '0028_plansaas_empresa_auto_suspender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaimpresion',
            name='contenido_esc_pos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaimpresion',
            name='documento_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaimpresion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='colaimpresion',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colaimpresion',
            name='contenido_raw',
            field=models.TextField(blank=True, null=True, verbose_name='Comandos ESC/POS RAW'),
        ),
    ]
