# Generated by Django 5.2.7 on 2026-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_colaimpresion_contenido_esc_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaimpresion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('imprimiendo', 'Imprimiendo'), ('impreso', 'Impreso'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
