# Generated by Django 5.1.5 on 2025-09-30 02:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articulos", "0007_alter_articulo_impuesto_especifico"),
        ("empresas", "0005_remove_configuracionempresa_formato_boletas_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(max_length=200, verbose_name="Proveedor"),
                ),
                (
                    "numero_orden",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Orden"
                    ),
                ),
                (
                    "fecha_orden",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Orden"
                    ),
                ),
                (
                    "fecha_entrega_esperada",
                    models.DateField(verbose_name="Fecha de Entrega Esperada"),
                ),
                (
                    "fecha_entrega_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Real"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("pendiente_aprobacion", "Pendiente de Aprobación"),
                            ("aprobada", "Aprobada"),
                            ("en_proceso", "En Proceso"),
                            ("parcialmente_recibida", "Parcialmente Recibida"),
                            ("completamente_recibida", "Completamente Recibida"),
                            ("cancelada", "Cancelada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="borrador",
                        max_length=30,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "condiciones_pago",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Condiciones de Pago"
                    ),
                ),
                (
                    "plazo_entrega",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Plazo de Entrega"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
                "ordering": ["-fecha_orden", "-numero_orden"],
            },
        ),
        migrations.CreateModel(
            name="ItemOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_solicitada",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Cantidad Solicitada",
                    ),
                ),
                (
                    "cantidad_recibida",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Cantidad Recibida",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "descuento_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Descuento Unitario",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Subtotal"
                    ),
                ),
                (
                    "especificaciones",
                    models.TextField(blank=True, verbose_name="Especificaciones"),
                ),
                (
                    "fecha_entrega_item",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega del Item"
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "orden_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="compras.ordencompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Orden de Compra",
                "verbose_name_plural": "Items de Órdenes de Compra",
                "unique_together": {("orden_compra", "articulo")},
            },
        ),
        migrations.CreateModel(
            name="CuentaCorrienteProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(max_length=200, verbose_name="Proveedor"),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Movimiento",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("compra", "Compra"),
                            ("pago", "Pago"),
                            ("nota_credito", "Nota de Crédito"),
                            ("nota_debito", "Nota de Débito"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "factura_proveedor",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Número de Factura del Proveedor",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Monto"
                    ),
                ),
                (
                    "saldo_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Saldo Anterior"
                    ),
                ),
                (
                    "saldo_nuevo",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Saldo Nuevo"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "orden_compra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compras.ordencompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Cuenta Corriente de Proveedor",
                "verbose_name_plural": "Movimientos de Cuenta Corriente de Proveedores",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RecepcionMercancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_recepcion",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Recepción"
                    ),
                ),
                (
                    "fecha_recepcion",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Recepción",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_revision", "En Revisión"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "transportista",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Transportista"
                    ),
                ),
                (
                    "numero_guia",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de Guía",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "orden_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recepciones",
                        to="compras.ordencompra",
                    ),
                ),
                (
                    "recibido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recepciones_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recepción de Mercancía",
                "verbose_name_plural": "Recepciones de Mercancías",
                "ordering": ["-fecha_recepcion", "-numero_recepcion"],
            },
        ),
        migrations.CreateModel(
            name="ItemRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_recibida",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Cantidad Recibida",
                    ),
                ),
                (
                    "calidad_aceptable",
                    models.BooleanField(default=True, verbose_name="Calidad Aceptable"),
                ),
                (
                    "observaciones_calidad",
                    models.TextField(
                        blank=True, verbose_name="Observaciones de Calidad"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "item_orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compras.itemordencompra",
                    ),
                ),
                (
                    "recepcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="compras.recepcionmercancia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Recepción",
                "verbose_name_plural": "Items de Recepción",
                "unique_together": {("recepcion", "item_orden")},
            },
        ),
    ]
