# Generated by Django 5.1.5 on 2025-09-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0001_initial"),
    ]

    operations = []
