# Generated by Django 5.1.5 on 2025-09-30 15:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodegas", "0002_remove_bodega_capacidad_maxima_and_more"),
        ("compras", "0002_auto_20250930_1221"),
        ("empresas", "0005_remove_configuracionempresa_formato_boletas_and_more"),
        ("proveedores", "0002_alter_proveedor_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemordencompra",
            options={
                "ordering": ["id"],
                "verbose_name": "Item de Orden de Compra",
                "verbose_name_plural": "Items de Órdenes de Compra",
            },
        ),
        migrations.RemoveField(
            model_name="itemordencompra",
            name="descuento_unitario",
        ),
        migrations.RemoveField(
            model_name="ordencompra",
            name="descuento",
        ),
        migrations.RemoveField(
            model_name="ordencompra",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="ordencompra",
            name="iva",
        ),
        migrations.RemoveField(
            model_name="ordencompra",
            name="total",
        ),
        migrations.AddField(
            model_name="itemordencompra",
            name="descuento_monto",
            field=models.IntegerField(default=0, verbose_name="Descuento Monto"),
        ),
        migrations.AddField(
            model_name="itemordencompra",
            name="descuento_porcentaje",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Descuento (%)",
            ),
        ),
        migrations.AddField(
            model_name="itemordencompra",
            name="impuesto_monto",
            field=models.IntegerField(default=0, verbose_name="Impuesto Monto"),
        ),
        migrations.AddField(
            model_name="itemordencompra",
            name="impuesto_porcentaje",
            field=models.IntegerField(
                default=19,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Impuesto (%)",
            ),
        ),
        migrations.AddField(
            model_name="itemordencompra",
            name="total_item",
            field=models.IntegerField(default=0, verbose_name="Total Item"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="bodega",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bodegas.bodega",
                verbose_name="Bodega",
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="descuentos_totales",
            field=models.IntegerField(default=0, verbose_name="Descuentos Totales"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="en_cuenta_corriente",
            field=models.BooleanField(
                default=False, verbose_name="En Cuenta Corriente"
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="estado_orden",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("pendiente_aprobacion", "Pendiente de Aprobación"),
                    ("aprobada", "Aprobada"),
                    ("en_proceso", "En Proceso"),
                    ("parcialmente_recibida", "Parcialmente Recibida"),
                    ("completamente_recibida", "Completamente Recibida"),
                    ("cancelada", "Cancelada"),
                    ("cerrada", "Cerrada"),
                ],
                default="borrador",
                max_length=30,
                verbose_name="Estado de la Orden",
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("pagada", "Pagada"),
                    ("credito", "Crédito"),
                    ("parcial", "Pago Parcial"),
                    ("vencida", "Vencida"),
                ],
                default="credito",
                max_length=20,
                verbose_name="Estado de Pago",
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="fecha_registro_cc",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha Registro CC"
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="impuestos_totales",
            field=models.IntegerField(default=0, verbose_name="Impuestos Totales"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="monto_pagado",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Monto Pagado"
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="saldo_pendiente",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Saldo Pendiente",
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="total_orden",
            field=models.IntegerField(default=0, verbose_name="Total Orden"),
        ),
        migrations.AlterField(
            model_name="itemordencompra",
            name="cantidad_recibida",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Cantidad Recibida",
            ),
        ),
        migrations.AlterField(
            model_name="itemordencompra",
            name="cantidad_solicitada",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cantidad Solicitada",
            ),
        ),
        migrations.AlterField(
            model_name="itemordencompra",
            name="orden_compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="compras.ordencompra",
                verbose_name="Orden de Compra",
            ),
        ),
        migrations.AlterField(
            model_name="itemordencompra",
            name="precio_unitario",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.AlterField(
            model_name="itemordencompra",
            name="subtotal",
            field=models.IntegerField(default=0, verbose_name="Subtotal"),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordenes_compra_creadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="fecha_aprobacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Aprobación"
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Modificación"
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("normal", "Normal"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Prioridad",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="proveedores.proveedor",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="subtotal",
            field=models.IntegerField(default=0, verbose_name="Subtotal"),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
