# Generated by Django 5.1.5 on 2025-09-30 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_update_orden_compra_model"),
        ("empresas", "0005_remove_configuracionempresa_formato_boletas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordencompra",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
