# Generated by Django 4.2.7 on 2025-10-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0004_alter_ordencompra_sucursal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CuentaCorrienteProveedor",
        ),
    ]
