# Generated by Django 5.1.5 on 2025-10-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0005_delete_cuentacorrienteproveedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordencompra",
            name="estado_orden",
            field=models.CharField(
                choices=[
                    ("en_proceso", "En Proceso"),
                    ("aprobada", "Aprobada"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                ],
                default="en_proceso",
                max_length=30,
                verbose_name="Estado de la Orden",
            ),
        ),
    ]
