# Generated by Django 4.2.13 on 2026-04-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0006_alter_ordencompra_estado_orden"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="descuento_global_monto",
            field=models.IntegerField(default=0, verbose_name="Desc. Global $"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="descuento_global_porcentaje",
            field=models.IntegerField(default=0, verbose_name="Desc. Global %"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="impuesto_especifico",
            field=models.IntegerField(default=0, verbose_name="Impuesto Específico"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="iva_ajustado",
            field=models.IntegerField(default=0, verbose_name="IVA Final"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="neto_ajustado",
            field=models.IntegerField(default=0, verbose_name="Neto Final"),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="subtotal",
            field=models.IntegerField(default=0, verbose_name="Subtotal (Items)"),
        ),
    ]
