# Generated by Django 4.2.13 on 2026-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0007_ordencompra_descuento_global_monto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordencompra",
            name="descuento_global_monto",
        ),
        migrations.RemoveField(
            model_name="ordencompra",
            name="descuento_global_porcentaje",
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="descuento_monto_directo",
            field=models.IntegerField(default=0, verbose_name="Descuento Directo ($)"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="descuento_porcentaje_1",
            field=models.IntegerField(default=0, verbose_name="Descuento 1 (%)"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="descuento_porcentaje_2",
            field=models.IntegerField(default=0, verbose_name="Descuento 2 (%)"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="descuento_porcentaje_3",
            field=models.IntegerField(default=0, verbose_name="Descuento 3 (%)"),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="descuentos_totales",
            field=models.IntegerField(default=0, verbose_name="Suma de Descuentos"),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="subtotal",
            field=models.IntegerField(default=0, verbose_name="Subtotal (Items Bruto)"),
        ),
    ]
