# Generated by Django 5.2.7 on 2026-06-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_remove_ordencompra_descuento_global_monto_and_more'),
        ('empresas', '0028_plansaas_empresa_auto_suspender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado_orden',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('aprobada', 'Aprobada'), ('parcialmente_recibida', 'Parcialmente Recibida'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='en_proceso', max_length=30, verbose_name='Estado de la Orden'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='numero_orden',
            field=models.CharField(max_length=20, verbose_name='Número de Orden'),
        ),
        migrations.AlterUniqueTogether(
            name='ordencompra',
            unique_together={('empresa', 'numero_orden')},
        ),
    ]
