# Generated by Django 5.2.7 on 2026-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_ordencompra_estado_orden_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordencompra',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='numero_orden',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Orden'),
        ),
    ]
