# Generated by Django 5.1.5 on 2025-09-30 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_remove_configuracionempresa_formato_boletas_and_more"),
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="proveedor",
            unique_together={("empresa", "rut")},
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="codigo",
        ),
    ]
