# Generated by Django 4.2.13 on 2025-12-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0002_alter_proveedor_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="region",
            field=models.CharField(blank=True, max_length=100, verbose_name="Región"),
        ),
    ]
