# Generated by Django 5.1.5 on 2025-09-26 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Empresa"
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón Social"),
                ),
                (
                    "rut",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El RUT debe tener el formato XX.XXX.XXX-X",
                                regex="^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$",
                            )
                        ],
                        verbose_name="RUT",
                    ),
                ),
                (
                    "giro",
                    models.CharField(max_length=200, verbose_name="Giro Comercial"),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                ("comuna", models.CharField(max_length=100, verbose_name="Comuna")),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                ("region", models.CharField(max_length=100, verbose_name="Región")),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "sitio_web",
                    models.URLField(blank=True, null=True, verbose_name="Sitio Web"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="empresas/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "color_primario",
                    models.CharField(
                        default="#2C3E50", max_length=7, verbose_name="Color Primario"
                    ),
                ),
                (
                    "color_secundario",
                    models.CharField(
                        default="#E74C3C", max_length=7, verbose_name="Color Secundario"
                    ),
                ),
                (
                    "regimen_tributario",
                    models.CharField(
                        choices=[
                            ("19", "19% IVA"),
                            ("exento", "Exento de IVA"),
                            ("otro", "Otro"),
                        ],
                        default="19",
                        max_length=50,
                        verbose_name="Régimen Tributario",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("inactiva", "Inactiva"),
                            ("suspendida", "Suspendida"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nombre"],
                "unique_together": {("rut",)},
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefijo_facturas",
                    models.CharField(
                        default="F", max_length=10, verbose_name="Prefijo Facturas"
                    ),
                ),
                (
                    "prefijo_boletas",
                    models.CharField(
                        default="B", max_length=10, verbose_name="Prefijo Boletas"
                    ),
                ),
                (
                    "prefijo_guias",
                    models.CharField(
                        default="G", max_length=10, verbose_name="Prefijo Guías"
                    ),
                ),
                (
                    "siguiente_factura",
                    models.IntegerField(
                        default=1, verbose_name="Siguiente Número Factura"
                    ),
                ),
                (
                    "siguiente_boleta",
                    models.IntegerField(
                        default=1, verbose_name="Siguiente Número Boleta"
                    ),
                ),
                (
                    "siguiente_guia",
                    models.IntegerField(
                        default=1, verbose_name="Siguiente Número Guía"
                    ),
                ),
                (
                    "imprimir_logo",
                    models.BooleanField(
                        default=True, verbose_name="Imprimir Logo en Documentos"
                    ),
                ),
                (
                    "pie_pagina_documentos",
                    models.TextField(
                        blank=True, verbose_name="Pie de Página en Documentos"
                    ),
                ),
                (
                    "alerta_stock_minimo",
                    models.BooleanField(
                        default=True, verbose_name="Alertas de Stock Mínimo"
                    ),
                ),
                (
                    "notificar_vencimientos",
                    models.BooleanField(
                        default=True, verbose_name="Notificar Vencimientos"
                    ),
                ),
                (
                    "respaldo_automatico",
                    models.BooleanField(
                        default=True, verbose_name="Respaldo Automático"
                    ),
                ),
                (
                    "frecuencia_respaldo",
                    models.CharField(
                        choices=[
                            ("diario", "Diario"),
                            ("semanal", "Semanal"),
                            ("mensual", "Mensual"),
                        ],
                        default="diario",
                        max_length=20,
                        verbose_name="Frecuencia de Respaldo",
                    ),
                ),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Empresa",
                "verbose_name_plural": "Configuraciones de Empresas",
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Sucursal"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, verbose_name="Código de Sucursal"),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                ("comuna", models.CharField(max_length=100, verbose_name="Comuna")),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                ("region", models.CharField(max_length=100, verbose_name="Región")),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False, verbose_name="Es Sucursal Principal"
                    ),
                ),
                ("horario_apertura", models.TimeField(verbose_name="Hora de Apertura")),
                ("horario_cierre", models.TimeField(verbose_name="Hora de Cierre")),
                (
                    "gerente",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Gerente"
                    ),
                ),
                (
                    "telefono_gerente",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono del Gerente",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("inactiva", "Inactiva"),
                            ("en_construccion", "En Construcción"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "ordering": ["empresa", "nombre"],
                "unique_together": {("empresa", "codigo")},
            },
        ),
    ]
