# Generated by Django 5.2.6 on 2025-09-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresa_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="color_primario",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="color_secundario",
        ),
    ]
