# Generated by Django 4.2.7 on 2025-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_remove_empresa_color_primario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionempresa",
            name="formato_ajustes",
            field=models.CharField(
                default="{prefijo}-{000}", max_length=20, verbose_name="Formato Ajustes"
            ),
        ),
        migrations.AddField(
            model_name="configuracionempresa",
            name="formato_boletas",
            field=models.CharField(
                default="{prefijo}-{000}", max_length=20, verbose_name="Formato Boletas"
            ),
        ),
        migrations.AddField(
            model_name="configuracionempresa",
            name="formato_facturas",
            field=models.CharField(
                default="{prefijo}-{000}",
                max_length=20,
                verbose_name="Formato Facturas",
            ),
        ),
        migrations.AddField(
            model_name="configuracionempresa",
            name="formato_guias",
            field=models.CharField(
                default="{prefijo}-{000}", max_length=20, verbose_name="Formato Guías"
            ),
        ),
        migrations.AddField(
            model_name="configuracionempresa",
            name="prefijo_ajustes",
            field=models.CharField(
                default="Aju", max_length=10, verbose_name="Prefijo Ajustes"
            ),
        ),
        migrations.AddField(
            model_name="configuracionempresa",
            name="siguiente_ajuste",
            field=models.IntegerField(
                default=1, verbose_name="Siguiente Número Ajuste"
            ),
        ),
    ]
