# Generated by Django 4.2.7 on 2025-09-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_configuracionempresa_formato_ajustes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracionempresa",
            name="formato_boletas",
        ),
        migrations.RemoveField(
            model_name="configuracionempresa",
            name="formato_facturas",
        ),
        migrations.RemoveField(
            model_name="configuracionempresa",
            name="formato_guias",
        ),
        migrations.RemoveField(
            model_name="configuracionempresa",
            name="prefijo_boletas",
        ),
        migrations.RemoveField(
            model_name="configuracionempresa",
            name="prefijo_facturas",
        ),
        migrations.RemoveField(
            model_name="configuracionempresa",
            name="prefijo_guias",
        ),
        migrations.RemoveField(
            model_name="configuracionempresa",
            name="siguiente_boleta",
        ),
        migrations.RemoveField(
            model_name="configuracionempresa",
            name="siguiente_factura",
        ),
        migrations.RemoveField(
            model_name="configuracionempresa",
            name="siguiente_guia",
        ),
    ]
