# Generated by Django 4.2.7 on 2025-10-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_remove_configuracionempresa_formato_boletas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionempresa",
            name="formato_orden_compra",
            field=models.CharField(
                default="{prefijo}-{000}",
                max_length=20,
                verbose_name="Formato Órdenes de Compra",
            ),
        ),
        migrations.AddField(
            model_name="configuracionempresa",
            name="prefijo_orden_compra",
            field=models.CharField(
                default="OC", max_length=10, verbose_name="Prefijo Órdenes de Compra"
            ),
        ),
        migrations.AddField(
            model_name="configuracionempresa",
            name="siguiente_orden_compra",
            field=models.IntegerField(
                default=1, verbose_name="Siguiente Número Orden de Compra"
            ),
        ),
    ]
