# Generated by Django 5.1.5 on 2025-10-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_configuracionempresa_formato_orden_compra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="ambiente_sii",
            field=models.CharField(
                choices=[
                    ("certificacion", "Certificación (Pruebas)"),
                    ("produccion", "Producción"),
                ],
                default="certificacion",
                max_length=20,
                verbose_name="Ambiente SII",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="certificado_digital",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="empresas/certificados/",
                verbose_name="Certificado Digital (.p12/.pfx)",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="ciudad_casa_matriz",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Ciudad Casa Matriz"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="codigo_actividad_economica",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Código Actividad Económica"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="comuna_casa_matriz",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Comuna Casa Matriz"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="direccion_casa_matriz",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Dirección Casa Matriz"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="email_contacto_sii",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email de Contacto SII"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="email_intercambio",
            field=models.EmailField(
                blank=True,
                max_length=254,
                verbose_name="Email para Intercambio (Acuses)",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="facturacion_electronica",
            field=models.BooleanField(
                default=False, verbose_name="Facturación Electrónica Activa"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="giro_sii",
            field=models.CharField(blank=True, max_length=200, verbose_name="Giro SII"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="password_certificado",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Contraseña del Certificado"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="razon_social_sii",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Razón Social SII"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="resolucion_fecha",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Resolución SII"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="resolucion_numero",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número Resolución SII"
            ),
        ),
    ]
