# Generated by Django 5.1.5 on 2025-10-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0007_empresa_ambiente_sii_empresa_certificado_digital_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="alerta_folios_minimos",
            field=models.IntegerField(
                default=20,
                help_text="Cantidad de folios restantes para activar alerta de agotamiento",
                verbose_name="Alerta de Folios Mínimos",
            ),
        ),
    ]
