# Generated by Django 5.1.5 on 2025-10-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0008_empresa_alerta_folios_minimos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="alerta_folios_minimos",
        ),
    ]
