# Generated by Django 5.1.5 on 2025-10-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0009_remove_empresa_alerta_folios_minimos"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="alerta_folios_minimos",
            field=models.IntegerField(
                default=10,
                help_text="Cantidad de folios restantes para comenzar a alertar por documento",
                verbose_name="Folios Mínimos para Alerta",
            ),
        ),
    ]
