# Generated by Django 5.1.5 on 2025-10-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0010_empresa_alerta_folios_minimos"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="oficina_sii",
            field=models.CharField(
                blank=True,
                help_text="Oficina regional del SII donde está registrada la empresa",
                max_length=100,
                verbose_name="Oficina SII",
            ),
        ),
    ]
