# Generated by Django 5.1.5 on 2025-10-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0012_empresa_tipo_industria"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="modo_reutilizacion_folios",
            field=models.BooleanField(
                default=False,
                help_text="Permite reutilizar folios para pruebas (solo en certificación)",
                verbose_name="Modo Reutilización de Folios",
            ),
        ),
    ]
