# Generated by Django 5.1.5 on 2025-10-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0013_empresa_modo_reutilizacion_folios"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="impresora_boleta",
            field=models.CharField(
                choices=[
                    ("laser", "Impresora Láser/Inyección (A4)"),
                    ("termica", "Impresora Térmica (80mm)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir boletas electrónicas",
                max_length=10,
                verbose_name="Impresora para Boletas Electrónicas",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_cotizacion",
            field=models.CharField(
                choices=[
                    ("laser", "Impresora Láser/Inyección (A4)"),
                    ("termica", "Impresora Térmica (80mm)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir cotizaciones",
                max_length=10,
                verbose_name="Impresora para Cotizaciones",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_factura",
            field=models.CharField(
                choices=[
                    ("laser", "Impresora Láser/Inyección (A4)"),
                    ("termica", "Impresora Térmica (80mm)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir facturas electrónicas",
                max_length=10,
                verbose_name="Impresora para Facturas Electrónicas",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_guia",
            field=models.CharField(
                choices=[
                    ("laser", "Impresora Láser/Inyección (A4)"),
                    ("termica", "Impresora Térmica (80mm)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir guías de despacho",
                max_length=10,
                verbose_name="Impresora para Guías de Despacho",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_nota_credito",
            field=models.CharField(
                choices=[
                    ("laser", "Impresora Láser/Inyección (A4)"),
                    ("termica", "Impresora Térmica (80mm)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir notas de crédito",
                max_length=10,
                verbose_name="Impresora para Notas de Crédito",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_nota_debito",
            field=models.CharField(
                choices=[
                    ("laser", "Impresora Láser/Inyección (A4)"),
                    ("termica", "Impresora Térmica (80mm)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir notas de débito",
                max_length=10,
                verbose_name="Impresora para Notas de Débito",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_vale",
            field=models.CharField(
                choices=[
                    ("laser", "Impresora Láser/Inyección (A4)"),
                    ("termica", "Impresora Térmica (80mm)"),
                ],
                default="termica",
                help_text="Tipo de impresora a usar para imprimir vales y tickets de venta",
                max_length=10,
                verbose_name="Impresora para Vales/Tickets",
            ),
        ),
    ]
