# Generated by Django 4.2.13 on 2025-10-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0014_agregar_config_impresoras"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="tipo_industria",
        ),
        migrations.AddField(
            model_name="empresa",
            name="max_descuento_linea",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje máximo de descuento permitido por cada producto en una venta.",
                max_digits=5,
                verbose_name="Descuento Máximo por Línea (%)",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="max_descuento_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje máximo de descuento permitido sobre el total del documento de venta.",
                max_digits=5,
                verbose_name="Descuento Máximo por Total (%)",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="opera_con_despacho_movil",
            field=models.BooleanField(
                default=False,
                help_text="Si se activa, se solicitarán datos de vehículo y chofer al imprimir documentos de despacho.",
                verbose_name="¿Opera con Despacho Móvil?",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="usa_produccion",
            field=models.BooleanField(
                default=False,
                help_text="Activa las funcionalidades de gestión de recetas y órdenes de producción.",
                verbose_name="¿Usa Módulo de Producción?",
            ),
        ),
    ]
