# Generated by Django 4.2.13 on 2025-10-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0015_remove_empresa_tipo_industria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="tipo_industria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("textil", "Textil y Confección"),
                    ("carnico", "Cárnico y Alimenticio"),
                    ("panaderia", "Panadería y Pastelería"),
                    ("quimico", "Químico y Farmacéutico"),
                    ("otro", "Otro"),
                ],
                help_text="Define el tipo de industria para adaptar formularios de producción",
                max_length=20,
                null=True,
                verbose_name="Tipo de Industria",
            ),
        ),
    ]
