# Generated by Django 4.2.13 on 2025-10-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0016_empresa_tipo_industria"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="usa_despacho_movil",
            field=models.BooleanField(
                default=False,
                help_text="Requiere asignación de vehículo y chofer al generar documentos de despacho.",
                verbose_name="¿Usa Despacho Móvil?",
            ),
        ),
    ]
