# Generated by Django 4.2.13 on 2025-10-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0017_empresa_usa_despacho_movil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="max_descuento_linea",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="max_descuento_total",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="opera_con_despacho_movil",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="usa_despacho_movil",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="usa_produccion",
        ),
    ]
