# Generated by Django 4.2.13 on 2025-10-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0018_remove_empresa_max_descuento_linea_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="max_descuento_lineal",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje máximo de descuento permitido por cada producto en una venta",
                max_digits=5,
                verbose_name="Máximo Descuento por Línea (%)",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="max_descuento_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje máximo de descuento permitido sobre el total de una venta",
                max_digits=5,
                verbose_name="Máximo Descuento Total (%)",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="usa_produccion",
            field=models.BooleanField(
                default=False,
                help_text="Habilita las funciones de recetas y órdenes de producción",
                verbose_name="Activar Módulo de Producción",
            ),
        ),
    ]
