# Generated by Django 4.2.13 on 2025-10-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0019_empresa_max_descuento_lineal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="usa_sistema_despacho",
            field=models.BooleanField(
                default=False,
                help_text="Solicita móvil y chofer al procesar ventas para generar hojas de ruta",
                verbose_name="Usar Sistema de Despacho",
            ),
        ),
    ]
