# Generated by Django 4.2.13 on 2025-10-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0020_empresa_usa_sistema_despacho"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="impresora_boleta_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la impresora física instalada en el sistema",
                max_length=200,
                null=True,
                verbose_name="Nombre físico impresora boletas",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_cotizacion_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la impresora física instalada en el sistema",
                max_length=200,
                null=True,
                verbose_name="Nombre físico impresora cotizaciones",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_factura_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la impresora física instalada en el sistema",
                max_length=200,
                null=True,
                verbose_name="Nombre físico impresora facturas",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_guia_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la impresora física instalada en el sistema",
                max_length=200,
                null=True,
                verbose_name="Nombre físico impresora guías",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_nota_credito_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la impresora física instalada en el sistema",
                max_length=200,
                null=True,
                verbose_name="Nombre físico impresora notas crédito",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_nota_debito_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la impresora física instalada en el sistema",
                max_length=200,
                null=True,
                verbose_name="Nombre físico impresora notas débito",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="impresora_vale_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la impresora física instalada en el sistema",
                max_length=200,
                null=True,
                verbose_name="Nombre físico impresora vales",
            ),
        ),
    ]
