# Generated by Django 4.2.13 on 2025-10-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0021_empresa_impresora_boleta_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="max_articulos_factura_laser",
            field=models.IntegerField(
                default=100,
                help_text="Máximo de líneas de artículos permitidas en una factura para impresora láser",
                verbose_name="Máx. Artículos en Factura (Láser/A4)",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="max_articulos_factura_termica",
            field=models.IntegerField(
                default=30,
                help_text="Máximo de líneas de artículos permitidas en una factura para impresora térmica",
                verbose_name="Máx. Artículos en Factura (Térmica/80mm)",
            ),
        ),
    ]
