# Generated by Django 4.2.13 on 2025-11-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0022_empresa_max_articulos_factura_laser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="max_articulos_factura_laser",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="max_articulos_factura_termica",
        ),
    ]
