# Generated by Django 4.2.13 on 2025-11-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0023_remove_empresa_max_articulos_factura_laser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="Clave API para autenticación en el servicio de documentos electrónicos",
                max_length=255,
                null=True,
                verbose_name="API KEY",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="api_url",
            field=models.URLField(
                blank=True,
                help_text="URL del servicio API para envío de documentos electrónicos",
                null=True,
                verbose_name="API URL",
            ),
        ),
    ]
