# Generated by Django 4.2.13 on 2025-11-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0024_empresa_api_key_empresa_api_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="dtebox_ambiente",
            field=models.CharField(
                blank=True,
                choices=[("T", "Homologación (T)"), ("P", "Producción (P)")],
                default="T",
                help_text="T para Homologación, P para Producción",
                max_length=1,
                verbose_name="Ambiente DTEBox",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="dtebox_auth_key",
            field=models.CharField(
                blank=True,
                help_text="Llave de autenticación para DTEBox",
                max_length=255,
                null=True,
                verbose_name="DTEBox Auth Key",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="dtebox_habilitado",
            field=models.BooleanField(
                default=False,
                help_text="Activar timbraje offline mediante DTEBox",
                verbose_name="DTEBox Habilitado",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="dtebox_pdf417_columns",
            field=models.IntegerField(
                blank=True,
                default=5,
                help_text="Número de columnas para el código PDF417",
                null=True,
                verbose_name="PDF417 Columns",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="dtebox_pdf417_level",
            field=models.IntegerField(
                blank=True,
                default=2,
                help_text="Nivel del código PDF417",
                null=True,
                verbose_name="PDF417 Level",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="dtebox_pdf417_type",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Tipo del código PDF417",
                null=True,
                verbose_name="PDF417 Type",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="dtebox_url",
            field=models.URLField(
                blank=True,
                help_text="URL del servidor DTEBox (ej: http://192.168.1.100/api/Core.svc/core/SendDocumentAsXML)",
                null=True,
                verbose_name="DTEBox URL",
            ),
        ),
    ]
