# Generated by Django 4.2.13 on 2025-12-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0025_empresa_dtebox_ambiente_empresa_dtebox_auth_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionempresa",
            name="prefijo_ajustes",
            field=models.CharField(
                default="AJU", max_length=10, verbose_name="Prefijo Ajustes"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="giro",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Giro Comercial"
            ),
        ),
    ]
