# Generated by Django 4.2.13 on 2026-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0026_hacer_giro_opcional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="impresora_boleta_nombre",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="impresora_cotizacion_nombre",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="impresora_factura_nombre",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="impresora_guia_nombre",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="impresora_nota_credito_nombre",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="impresora_nota_debito_nombre",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="impresora_vale_nombre",
        ),
        migrations.AlterField(
            model_name="empresa",
            name="impresora_boleta",
            field=models.CharField(
                choices=[
                    ("laser", "Láser/Tinta (A4 - 210mm x 297mm)"),
                    ("termica_80", "Térmica 80mm (Tickets/Recibos)"),
                    ("termica_58", "Térmica 58mm (Tickets/Recibos)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir boletas electrónicas",
                max_length=10,
                verbose_name="Impresora para Boletas Electrónicas",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="impresora_cotizacion",
            field=models.CharField(
                choices=[
                    ("laser", "Láser/Tinta (A4 - 210mm x 297mm)"),
                    ("termica_80", "Térmica 80mm (Tickets/Recibos)"),
                    ("termica_58", "Térmica 58mm (Tickets/Recibos)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir cotizaciones",
                max_length=10,
                verbose_name="Impresora para Cotizaciones",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="impresora_factura",
            field=models.CharField(
                choices=[
                    ("laser", "Láser/Tinta (A4 - 210mm x 297mm)"),
                    ("termica_80", "Térmica 80mm (Tickets/Recibos)"),
                    ("termica_58", "Térmica 58mm (Tickets/Recibos)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir facturas electrónicas",
                max_length=10,
                verbose_name="Impresora para Facturas Electrónicas",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="impresora_guia",
            field=models.CharField(
                choices=[
                    ("laser", "Láser/Tinta (A4 - 210mm x 297mm)"),
                    ("termica_80", "Térmica 80mm (Tickets/Recibos)"),
                    ("termica_58", "Térmica 58mm (Tickets/Recibos)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir guías de despacho",
                max_length=10,
                verbose_name="Impresora para Guías de Despacho",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="impresora_nota_credito",
            field=models.CharField(
                choices=[
                    ("laser", "Láser/Tinta (A4 - 210mm x 297mm)"),
                    ("termica_80", "Térmica 80mm (Tickets/Recibos)"),
                    ("termica_58", "Térmica 58mm (Tickets/Recibos)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir notas de crédito",
                max_length=10,
                verbose_name="Impresora para Notas de Crédito",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="impresora_nota_debito",
            field=models.CharField(
                choices=[
                    ("laser", "Láser/Tinta (A4 - 210mm x 297mm)"),
                    ("termica_80", "Térmica 80mm (Tickets/Recibos)"),
                    ("termica_58", "Térmica 58mm (Tickets/Recibos)"),
                ],
                default="laser",
                help_text="Tipo de impresora a usar para imprimir notas de débito",
                max_length=10,
                verbose_name="Impresora para Notas de Débito",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="impresora_vale",
            field=models.CharField(
                choices=[
                    ("laser", "Láser/Tinta (A4 - 210mm x 297mm)"),
                    ("termica_80", "Térmica 80mm (Tickets/Recibos)"),
                    ("termica_58", "Térmica 58mm (Tickets/Recibos)"),
                ],
                default="termica_80",
                help_text="Tipo de impresora a usar para imprimir vales y tickets de venta",
                max_length=10,
                verbose_name="Impresora para Vales/Tickets",
            ),
        ),
    ]
