# Generated by Django 4.2.13 on 2026-03-25 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0027_remove_empresa_impresora_boleta_nombre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanSaaS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Plan"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "precio_mensual",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio Mensual"
                    ),
                ),
                (
                    "max_usuarios",
                    models.IntegerField(default=1, verbose_name="Máximo de Usuarios"),
                ),
                (
                    "max_sucursales",
                    models.IntegerField(default=1, verbose_name="Máximo de Sucursales"),
                ),
                (
                    "max_productos",
                    models.IntegerField(
                        default=100, verbose_name="Máximo de Productos"
                    ),
                ),
                (
                    "max_documentos_mes",
                    models.IntegerField(default=50, verbose_name="Máximo DTEs por Mes"),
                ),
                (
                    "incluye_produccion",
                    models.BooleanField(
                        default=False, verbose_name="Incluye Módulo Producción"
                    ),
                ),
                (
                    "incluye_despacho",
                    models.BooleanField(
                        default=False, verbose_name="Incluye Módulo Despacho"
                    ),
                ),
                (
                    "incluye_api",
                    models.BooleanField(
                        default=False, verbose_name="Incluye Acceso API"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Plan SaaS",
                "verbose_name_plural": "Planes SaaS",
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="auto_suspender",
            field=models.BooleanField(
                default=True, verbose_name="Suspender Automáticamente por No Pago"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="fecha_limite_pago",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Límite de Pago"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activa", "Activa"),
                    ("inactiva", "Inactiva"),
                    ("suspendida", "Suspendida (Mora)"),
                    ("demo", "Período de Prueba (Demo)"),
                ],
                default="activa",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=12)),
                ("comprobante_pago", models.CharField(blank=True, max_length=100)),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("pagado", "Pagado"),
                            ("pendiente", "Pendiente"),
                            ("vencido", "Vencido"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_suscripciones",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="empresas.plansaas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas_suscritas",
                to="empresas.plansaas",
                verbose_name="Plan Contratado",
            ),
        ),
    ]
